package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

public final class aC implements at {
    private static Map f972a;
    private static Map f973b;
    private static Map f974c;

    static {
        f972a = new HashMap();
        f973b = new HashMap();
        f974c = new HashMap();
    }

    public aC() {
        f972a.put(bO.AND_OTHER_FUNDING_SOURCES, "y otro");
        f972a.put(bO.AUTHENTICATING, "Autenticando");
        f972a.put(bO.BACK_BUTTON, "Atr\u00e1s");
        f972a.put(bO.BACKUP_FUNDING_SOURCE, "Garant\u00eda");
        f972a.put(bO.CANCEL, "Cancelar");
        f972a.put(bO.CARDTYPE_AMERICANEXPRESS, "American Express");
        f972a.put(bO.CARDTYPE_CARTAAURA, "Carta Aura");
        f972a.put(bO.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f972a.put(bO.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f972a.put(bO.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f972a.put(bO.CARDTYPE_COFINOGA, "Cofinoga");
        f972a.put(bO.CARDTYPE_DELTA, "Delta");
        f972a.put(bO.CARDTYPE_DISCOVER, "Discover");
        f972a.put(bO.CARDTYPE_ELECTRON, "Electron");
        f972a.put(bO.CARDTYPE_JCB, "JCB");
        f972a.put(bO.CARDTYPE_MAESTRO, "Maestro");
        f972a.put(bO.CARDTYPE_MASTERCARD, "MasterCard");
        f972a.put(bO.CARDTYPE_POSTEPAY, "Postepay");
        f972a.put(bO.CARDTYPE_4ETOILES, "4 \u00e9toiles");
        f972a.put(bO.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f972a.put(bO.CARDTYPE_VISA, "Visa");
        f972a.put(bO.CHANGE_PAYMENT_METHOD, "Cambiar forma de pago");
        f972a.put(bO.CHECKING_ACCOUNT_FOR_INSTITUTION, "Cheques");
        f972a.put(bO.CHECKING_DEVICE, "Comprobando el dispositivo\u2026");
        f972a.put(bO.CLEAR_CREDIT_CARD_INFO, "Borrar los datos de la tarjeta");
        f972a.put(bO.CONFIRM, "Confirmar");
        f972a.put(bO.CONFIRM_CLEAR_CREDIT_CARD_INFO, "\u00bfSeguro que desea borrar los datos de su tarjeta?");
        f972a.put(bO.CONFIRM_CHARGE_CREDIT_CARD, "Cargar en tarjeta");
        f972a.put(bO.CONFIRM_LOG_OUT, "\u00bfEst\u00e1 seguro que desea cerrar sesi\u00f3n de PayPal?");
        f972a.put(bO.CONFIRM_SEND_PAYMENT, "Enviar pago");
        f972a.put(bO.CONSENT_AGREEMENT_AGREE, "Aceptar");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Fecha de apertura de la cuenta");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Estado de cuenta");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Tipo de cuenta");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Direcci\u00f3n");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Intervalo de edades");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Fecha de nacimiento");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Direcci\u00f3n de correo electr\u00f3nico");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Nombre completo");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Sexo");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Idioma");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Configuraci\u00f3n regional");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Tel\u00e9fono");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Zona horaria");
        f972a.put(bO.CONSENT_AGREEMENT_ATTRIBUTES, "Compartir lo siguiente: %s.");
        f972a.put(bO.CONSENT_AGREEMENT_INTRO, "%s le solicita que usted:");
        f972a.put(bO.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Autorizar cargos</a> por futuras %2$s compras pagadas con PayPal. Le instruye a PayPal de pagar todos los importes solicitados por %3$s.");
        f972a.put(bO.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Acepte la <a href='%2$s'>pol\u00edtica de privacidad</a> y las <a href='%3$s'>condiciones de uso</a> de %1$s.");
        f972a.put(bO.CONSENT_AGREEMENT_TITLE, "Consentimiento");
        f972a.put(bO.EMAIL, "Correo electr\u00f3nico");
        f972a.put(bO.ENVIRONMENT_MOCK_DATA, "Datos de prueba");
        f972a.put(bO.ENVIRONMENT_SANDBOX, "Sandbox");
        f972a.put(bO.EXPIRES_ON_DATE, "Caduca");
        f972a.put(bO.FORGOT_PASSWORD, "\u00bfOlvid\u00f3 su contrase\u00f1a?");
        f972a.put(bO.FROM_ACCOUNT, "De");
        f972a.put(bO.FUTURE_PAYMENT_METHOD_QUESTION, "\u00bfC\u00f3mo le gustar\u00eda respaldar sus pagos futuros %1$s?");
        f972a.put(bO.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Su origen de fondos predeterminado se utilizar\u00e1 para pagar pagos futuros de PayPal realizados en este comercio.</p><p>Para cancelar este acuerdo, inicie sesi\u00f3n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Mi configuraci\u00f3n</strong> &gt; <strong>Iniciar sesi\u00f3n con PayPal</strong> y eliminar a este comercio de la lista.</p><p>Aplicar\u00e1 el art\u00edculo Pagos peri\u00f3dicos de las <a href='%s'>Condiciones de uso de PayPal</a>.</p><p>Para asegurarse de que los pagos funcionen bien con su cuenta PayPal, esta aplicaci\u00f3n podr\u00eda simular una peque\u00f1a transacci\u00f3n de prueba, pero no se transferir\u00e1 dinero alguno para esta prueba.</p>");
        f972a.put(bO.INTERNAL_ERROR, "Error interno");
        f972a.put(bO.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Al hacer clic en el bot\u00f3n a continuaci\u00f3n, por el presente documento acepto los t\u00e9rminos de las <a href='%1$s'>Condiciones de uso de PayPal</a> y declaro que cumplo las leyes y normas japonesas, incluidas las sanciones contra pagos a Corea del Norte e Ir\u00e1n de conformidad con la <a href='%2$s'>Ley de divisas y comercio exterior</a> para realizar la transacci\u00f3n.</p>");
        f972a.put(bO.LOG_IN, "Iniciar sesi\u00f3n");
        f972a.put(bO.LOG_IN_TO_PAYPAL, "Iniciar sesi\u00f3n con Paypal");
        f972a.put(bO.LOG_OUT_BUTTON, "Cerrar sesi\u00f3n");
        f972a.put(bO.LOG_OUT, "Cerrar sesi\u00f3n");
        f972a.put(bO.OK, "Aceptar");
        f972a.put(bO.PASSWORD, "Contrase\u00f1a");
        f972a.put(bO.PAY_AFTER_DELIVERY, "Pagar despu\u00e9s de la entrega");
        f972a.put(bO.PAY_WITH, "Pagar con");
        f972a.put(bO.PAY_WITH_CARD, "Pagar con tarjeta");
        f972a.put(bO.PAYPAL_BALANCE, "Saldo PayPal");
        f972a.put(bO.PHONE, "Tel\u00e9fono");
        f972a.put(bO.PIN, "NIP");
        f972a.put(bO.PREFERRED_PAYMENT_METHOD, "Forma de pago preferida");
        f972a.put(bO.PRIVACY, "PayPal protege su <a href='%s'>privacidad</a> e informaci\u00f3n financiera.");
        f972a.put(bO.PROCESSING, "Proceso en curso");
        f972a.put(bO.REMEMBER_CARD, "Recordar tarjeta");
        f972a.put(bO.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Ahorros");
        f972a.put(bO.SERVER_PROBLEM, "Se produjo un problema en la comunicaci\u00f3n con los servidores de PayPal. Intente de nuevo.");
        f972a.put(bO.SESSION_EXPIRED_MESSAGE, "Inicie sesi\u00f3n de nuevo en PayPal.");
        f972a.put(bO.SESSION_EXPIRED_TITLE, "Sesi\u00f3n caducada");
        f972a.put(bO.SHIPPING_ADDRESS, "Direcci\u00f3n de env\u00edo");
        f972a.put(bO.STAY_LOGGED_IN, "Mantener la sesi\u00f3n activa");
        f972a.put(bO.SYSTEM_ERROR_WITH_CODE, "Error de sistema (%s). Intente de nuevo m\u00e1s tarde.");
        f972a.put(bO.TRY_AGAIN, "Intente de nuevo");
        f972a.put(bO.TWO_FA_REQUIRED_ERROR, "No logra iniciar sesi\u00f3n, porque la autenticaci\u00f3n de dos factores fue activada para su cuenta.");
        f972a.put(bO.UNAUTHORIZED_DEVICE_MESSAGE, "No se permiten los pagos desde este dispositivo.");
        f972a.put(bO.UNAUTHORIZED_DEVICE_TITLE, "Dispositivo no autorizado");
        f972a.put(bO.UNAUTHORIZED_MERCHANT_MESSAGE, "Los pagos a este comercio no se permiten (id. de cliente no v\u00e1lida).");
        f972a.put(bO.UNAUTHORIZED_MERCHANT_TITLE, "Comercio no v\u00e1lido");
        f972a.put(bO.UNEXPECTED_PAYMENT_FLOW, "Hubo un problema al procesar su pago. Int\u00e9ntelo de nuevo.");
        f972a.put(bO.UNKNOWN_FUNDING_SOURCE, "Origen no reconocido");
        f972a.put(bO.WE_ARE_SORRY, "Lo sentimos");
        f972a.put(bO.YOUR_ORDER, "Su pedido");
        f972a.put(bO.CLEAR_CC_ALERT_TITLE, "\u00bfEliminar tarjeta?");
        f972a.put(bO.CONSENT_FAILED_ALERT_TITLE, "No se concluy\u00f3 el consentimiento");
        f972a.put(bO.CONNECTION_FAILED_TITLE, "Error de conexi\u00f3n");
        f972a.put(bO.LOGIN_FAILED_ALERT_TITLE, "Error de inicio de sesi\u00f3n");
        f972a.put(bO.LOGIN_WITH_EMAIL, "Iniciar sesi\u00f3n con contrase\u00f1a");
        f972a.put(bO.LOGIN_WITH_PHONE, "Iniciar sesi\u00f3n con NIP");
        f972a.put(bO.ONE_MOMENT, "Un momento\u2026");
        f972a.put(bO.PAY_FAILED_ALERT_TITLE, "Error de pago");
        f972a.put(bO.SCAN_CARD_ICON_DESCRIPTION, "Escanear");
        f972a.put(bO.VIA_LABEL, "V\u00eda");
        f972a.put(bO.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Error del sistema. Intente de nuevo m\u00e1s tarde.");
        f973b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Su origen de fondos predeterminado se utilizar\u00e1 para pagar pagos futuros de PayPal realizados en este comecio.</p><p>Su saldo PayPal o tarjeta de d\u00e9bito o cr\u00e9dito principal se utilizar\u00e1n para pagar sus compras de PayPal.</p><p>Para cancelar este acuerdo, inicie sesi\u00f3n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Mi configuraci\u00f3n</strong> &gt; <strong>Iniciar sesi\u00f3n con PayPal</strong> y eliminar a este comercio de la lista.</p>");
        f973b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Preaprobar pagos futuros realizados desde su <a href='%1$s'>cuenta PayPal</a>.");
        f973b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Autorizar cargos</a> por futuras %2$s compras pagadas con PayPal. Le instruye a PayPal de pagar todos los importes solicitados por %3$s.</p><p>Consulte los <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Pagos peri\u00f3dicos de PayPal y el Acuerdo de pagos</a> para obtener m\u00e1s informaci\u00f3n.</p>");
        f973b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autorizaci\u00f3n de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\u00f3n podr\u00eda simular una peque\u00f1a transacci\u00f3n de prueba, pero no se transferir\u00e1 pago alguno.</p><p>Su forma de pago predeterminada se utilizar\u00e1 para pagar las compras de PayPal.</p><p>Para cancelar esta autorizaci\u00f3n, inicie sesi\u00f3n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuraci\u00f3n de mi cuenta</strong> &gt; <strong>Iniciar sesi\u00f3n con PayPal</strong> y eliminar a este comercio de la lista.</p><p>Consulte el art\u00edculo \u00abPagos con aprobaci\u00f3n previa\u00bb de las <a href='%s'>Condiciones de uso de PayPal</a> para obtener m\u00e1s informaci\u00f3n.</p>");
        f973b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Autorizaci\u00f3n de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\u00f3n podr\u00eda simular una peque\u00f1a transacci\u00f3n de prueba, pero no se transferir\u00e1 pago alguno.</p><p>Su forma de pago predeterminada se utilizar\u00e1 para pagar las compras de PayPal.</p><p>Para cancelar esta autorizaci\u00f3n, inicie sesi\u00f3n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuraci\u00f3n de mi cuenta</strong> &gt; <strong>Iniciar sesi\u00f3n con PayPal</strong> y eliminar a este comercio de la lista.</p><p>Consulte el art\u00edculo \u00abPagos con aprobaci\u00f3n previa\u00bb de las <a href='%s'>Condiciones de uso de PayPal</a> para obtener m\u00e1s informaci\u00f3n.</p>");
        f973b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\u00f3n podr\u00eda simular una peque\u00f1a transacci\u00f3n de prueba, pero no se transferir\u00e1 dinero alguno.</p><p>Su forma de pago predeterminada (su saldo PayPal, cuenta bancaria asociada, tarjeta de d\u00e9bito o tarjeta de cr\u00e9dito, en ese orden) se utilizar\u00e1 para pagar sus compras de PayPal. Tenga en cuenta que si su forma de pago predeterminada no tiene suficientes fondos para cubrir la compra, su banco o el proveedor de su tarjeta podr\u00edan cobrarle una comisi\u00f3n.</p><p>Para cancelar este acuerdo, inicie sesi\u00f3n en su cuenta PayPal y vaya a <strong>Perfil</strong>, luego haga clic en <strong>Mi configuraci\u00f3n</strong> y <strong>Cambiar</strong> junto a \u00abIniciar sesi\u00f3n con PayPal\u00bb.</p>");
        f973b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Su origen de fondos predeterminado se utilizar\u00e1 para pagar pagos futuros de PayPal realizados en este comecio.</p><p>Su saldo PayPal o tarjeta de d\u00e9bito o cr\u00e9dito principal se utilizar\u00e1n para pagar sus compras de PayPal.</p><p>Para cancelar este acuerdo, inicie sesi\u00f3n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Mi configuraci\u00f3n</strong> &gt; <strong>Iniciar sesi\u00f3n con PayPal</strong> y eliminar a este comercio de la lista.</p>");
        f973b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>PayPal utilizar\u00e1 primero su Saldo PayPal para pagar por las compras. Si no cubre el total, su cuenta bancaria, cr\u00e9dito de PayPal, tarjeta de d\u00e9bito, tarjeta de cr\u00e9dito, y/o eCheck se utilizar\u00e1n para ese pedido.</p><p>Para cancelar este acuerdo, vaya a www.paypal.com <strong>Perfil</strong> &gt; <strong>Mi configuraci\u00f3n</strong> &gt; <strong>Iniciar sesi\u00f3n con PayPal</strong> y eliminar a este comercio de la lista.</p><p>Se puede requerir la autorizaci\u00f3n de un peque\u00f1o pago para garantizar que se puedan hacer cobros en su cuenta PayPal en el futuro. La autorizaci\u00f3n se anular\u00e1 y no se le har\u00e1 ning\u00fan cobro.</p>");
        f973b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\u00f3n podr\u00eda simular una peque\u00f1a transacci\u00f3n de prueba, pero no se transferir\u00e1 pago alguno.</p><p>Su forma de pago predeterminada se utilizar\u00e1 para pagar las compras de PayPal.</p><p>Para cancelar este acuerdo, inicie sesi\u00f3n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuraci\u00f3n</strong> &gt; <strong>Iniciar sesi\u00f3n con PayPal</strong> y eliminar a este comercio de la lista.</p>");
        f973b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Autorizaci\u00f3n de pago futuro</strong></h1><p>Para asegurarse de que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicaci\u00f3n podr\u00eda simular una peque\u00f1a transacci\u00f3n de prueba, pero no se transferir\u00e1 pago alguno.</p><p>Su forma de pago predeterminada se utilizar\u00e1 para pagar las compras de PayPal.</p><p>Para cancelar esta autorizaci\u00f3n, inicie sesi\u00f3n en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuraci\u00f3n de mi cuenta</strong> &gt; <strong>Iniciar sesi\u00f3n con PayPal</strong> y eliminar a este comercio de la lista.</p><p>Consulte el art\u00edculo \u00abPagos con aprobaci\u00f3n previa\u00bb de las <a href='%s'>Condiciones de uso de PayPal</a> para obtener m\u00e1s informaci\u00f3n.</p>");
        f973b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Autorizar cargos</a> por futuras %2$s compras pagadas con PayPal. Le instruye a PayPal de pagar todos los importes solicitados por %3$s.</p><p>Consulte los <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Pagos peri\u00f3dicos de PayPal y el Acuerdo de pagos</a> para obtener m\u00e1s informaci\u00f3n.</p>");
        f974c.put("INTERNAL_SERVICE_ERROR", "Error del sistema. Intente de nuevo m\u00e1s tarde.");
        f974c.put("EXPIRED_CREDIT_CARD", "La tarjeta ha caducado");
        f974c.put("EXPIRED_CREDIT_CARD_TOKEN", "Los datos de esta tarjeta ya no est\u00e1n registrados.\nEnv\u00edelos nuevamente.");
        f974c.put("INVALID_ACCOUNT_NUMBER", "Ese n\u00famero de cuenta no existe.");
        f974c.put("INVALID_RESOURCE_ID", "Error del sistema. Intente de nuevo m\u00e1s tarde.");
        f974c.put("DUPLICATE_REQUEST_ID", "Error del sistema. Intente de nuevo m\u00e1s tarde.");
        f974c.put("TRANSACTION_LIMIT_EXCEEDED", "El importe supera el l\u00edmite aceptable.");
        f974c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "El reembolso solicitado supera el importe de la transacci\u00f3n original.");
        f974c.put("REFUND_TIME_LIMIT_EXCEEDED", "Esta transacci\u00f3n es muy antigua para reembolsarse.");
        f974c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Esta transacci\u00f3n se ha reembolsado parcialmente.");
        f974c.put("TRANSACTION_ALREADY_REFUNDED", "Ya se reembols\u00f3 esta transacci\u00f3n.");
        f974c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "El importe supera el l\u00edmite aceptable.");
        f974c.put("AUTHORIZATION_ALREADY_COMPLETED", "Ya se realiz\u00f3 esta autorizaci\u00f3n.");
        f974c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Solo puede volver a aprobar la autorizaci\u00f3n original; no una nueva autorizaci\u00f3n.");
        f974c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "No se permite la nueva autorizaci\u00f3n en el per\u00edodo de tramitaci\u00f3n.");
        f974c.put("TOO_MANY_REAUTHORIZATIONS", "No se permiten nuevas autorizaciones para esta autorizaci\u00f3n.");
        f974c.put("PERMISSION_DENIED", "No hay permiso para la operaci\u00f3n solicitada.");
        f974c.put("AUTHORIZATION_VOIDED", "La autorizaci\u00f3n se anul\u00f3.");
        f974c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "La Id. de la autorizaci\u00f3n solicitada no existe.");
        f974c.put("VALIDATION_ERROR", "La informaci\u00f3n de pago no es v\u00e1lida. Corr\u00edjala y env\u00edela de nuevo.");
        f974c.put("CREDIT_CARD_REFUSED", "Tarjeta declinada.");
        f974c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Los datos de la tarjeta no son v\u00e1lidos. Corr\u00edjala y env\u00edela de nuevo.");
        f974c.put("PAYEE_ACCOUNT_RESTRICTED", "Este vendedor no puede recibir pagos por el momento.");
        f974c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "El pagador no ha aprobado el pago.");
        f974c.put("INVALID_PAYER_ID", "Error del sistema (la id. del pagador no es v\u00e1lida). Intente de nuevo m\u00e1s tarde.");
        f974c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Este vendedor no puede recibir pagos por el momento.");
        f974c.put("PAYMENT_APPROVAL_EXPIRED", "Caduc\u00f3 la aprobaci\u00f3n del pago.");
        f974c.put("PAYMENT_EXPIRED", "El pago caduc\u00f3.");
        f974c.put("DATA_RETRIEVAL", "Error del sistema. Intente de nuevo m\u00e1s tarde.");
        f974c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "La cuenta del beneficiario no dispone de un correo electr\u00f3nico confirmado.");
        f974c.put("PAYMENT_STATE_INVALID", "Esta solicitud no es v\u00e1lida debido al estado actual del pago.");
        f974c.put("TRANSACTION_REFUSED", "La transacci\u00f3n se declin\u00f3.");
        f974c.put("AMOUNT_MISMATCH", "El importe total de los art\u00edculos del carrito no coincide con el de la venta.");
        f974c.put("CURRENCY_NOT_ALLOWED", "Esta divisa no es compatible actualmente con PayPal.");
        f974c.put("CURRENCY_MISMATCH", "La divisa de la captura debe ser igual que la divisa de la autorizaci\u00f3n.");
        f974c.put("AUTHORIZATION_EXPIRED", "La autorizaci\u00f3n ha caducado.");
        f974c.put("INVALID_ARGUMENT", "La transacci\u00f3n se declin\u00f3 debido a un argumento no v\u00e1lido");
        f974c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "No puede acceder a la informaci\u00f3n de la tarjeta guardada.");
        f974c.put("CARD_TOKEN_PAYER_MISMATCH", "No puede acceder a la informaci\u00f3n de la tarjeta guardada.");
        f974c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "La autorizaci\u00f3n est\u00e1 en un estado que no se puede anular.");
        f974c.put("REQUIRED_SCOPE_MISSING", "Error del sistema. Intente de nuevo m\u00e1s tarde.");
        f974c.put("UNAUTHORIZED_PAYMENT", "El comercio PayPal no acepta este tipo de pagos.");
        f974c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Divisa no compatible para el tipo de tarjeta.");
        f974c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Tipo de tarjeta no compatible.");
        f974c.put("INSUFFICIENT_FUNDS", "El comprador no puede pagar - saldo insuficiente.");
        f974c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Hay una preferencia de perfil definida para rechazar autom\u00e1ticamente todas las transacciones.");
        f974c.put("INVALID_FACILITATOR_CONFIGURATION", "Esta transacci\u00f3n no puede procesarse debido a una configuraci\u00f3n no v\u00e1lida del facilitador.");
        f974c.put("ORDER_ALREADY_COMPLETED", "El pedido ya fue anulado, ha caducado o fue realizado.");
        f974c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Se ha llegado al n\u00famero m\u00e1ximo de autorizaciones permitidas para el pedido.");
        f974c.put("ORDER_VOIDED", "El pedido fue anulado.");
        f974c.put("ORDER_CANNOT_BE_VOIDED", "El pedido est\u00e1 en un estado que previene la anulaci\u00f3n.");
        f974c.put("ADDRESS_ADDITION_ERROR", "Error encontrado al agregar direcci\u00f3n de env\u00edo a cuenta PayPal.");
        f974c.put("INVALID_SHIPPING_ADDRESS", "La direcci\u00f3n de env\u00edo suministrada no es v\u00e1lida.");
        f974c.put("DUPLICATE_TRANSACTION", "Transacci\u00f3n duplicada.");
        f974c.put("AUTH_RC_RISK_FAILURE", "Declinado debido a riesgo.");
        f974c.put("AUTH_RC_OFAC_BLOCKED_IP", "Cliente no autorizado.");
        f974c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Cliente no autorizado.");
        f974c.put("invalid_user", "Nombre de usuario o contrase\u00f1a incorrectos. Intente de nuevo.");
        f974c.put("invalid_request", "Ha habido un error.");
        f974c.put("unauthorized_client", "Solicitud no autorizada.");
        f974c.put("access_denied", "Solicitud no autorizada.");
        f974c.put("unsupported_response_type", "Ha habido un error.");
        f974c.put("invalid_scope", "Solicitud no autorizada.");
        f974c.put("server_error", "Error del sistema. Intente de nuevo m\u00e1s tarde.");
        f974c.put("temporarily_unavailable", "Error del sistema. Intente de nuevo m\u00e1s tarde.");
    }

    public final String m877a() {
        return "es_MX";
    }

    public final /* synthetic */ String m878a(Enum enumR, String str) {
        bO bOVar = (bO) enumR;
        String str2 = bOVar.toString() + "|" + str;
        return f973b.containsKey(str2) ? (String) f973b.get(str2) : (String) f972a.get(bOVar);
    }

    public final String m879a(String str) {
        return (String) f974c.get(str);
    }
}
