package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

public final class aD implements at {
    private static Map f975a;
    private static Map f976b;
    private static Map f977c;

    static {
        f975a = new HashMap();
        f976b = new HashMap();
        f977c = new HashMap();
    }

    public aD() {
        f975a.put(bO.AND_OTHER_FUNDING_SOURCES, "et autre(s)");
        f975a.put(bO.AUTHENTICATING, "Authentification");
        f975a.put(bO.BACK_BUTTON, "Retour");
        f975a.put(bO.BACKUP_FUNDING_SOURCE, "Secondaire");
        f975a.put(bO.CANCEL, "Annuler");
        f975a.put(bO.CARDTYPE_AMERICANEXPRESS, "American Express");
        f975a.put(bO.CARDTYPE_CARTAAURA, "Carta Aura");
        f975a.put(bO.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f975a.put(bO.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f975a.put(bO.CARDTYPE_CARTEBLEUE, "Carte bancaire");
        f975a.put(bO.CARDTYPE_COFINOGA, "Cofinoga");
        f975a.put(bO.CARDTYPE_DELTA, "Delta");
        f975a.put(bO.CARDTYPE_DISCOVER, "Discover");
        f975a.put(bO.CARDTYPE_ELECTRON, "Electron");
        f975a.put(bO.CARDTYPE_JCB, "JCB");
        f975a.put(bO.CARDTYPE_MAESTRO, "Maestro");
        f975a.put(bO.CARDTYPE_MASTERCARD, "MasterCard");
        f975a.put(bO.CARDTYPE_POSTEPAY, "Postepay");
        f975a.put(bO.CARDTYPE_4ETOILES, "4\u00a0\u00e9toiles");
        f975a.put(bO.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f975a.put(bO.CARDTYPE_VISA, "Visa");
        f975a.put(bO.CHANGE_PAYMENT_METHOD, "Modifier le mode de paiement");
        f975a.put(bO.CHECKING_ACCOUNT_FOR_INSTITUTION, "Courant");
        f975a.put(bO.CHECKING_DEVICE, "V\u00e9rification de l\u2019appareil\u2026");
        f975a.put(bO.CLEAR_CREDIT_CARD_INFO, "Effacer les informations de carte");
        f975a.put(bO.CONFIRM, "Confirmation");
        f975a.put(bO.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Souhaitez-vous vraiment effacer les informations relatives \u00e0 votre carte\u00a0?");
        f975a.put(bO.CONFIRM_CHARGE_CREDIT_CARD, "D\u00e9biter la carte");
        f975a.put(bO.CONFIRM_LOG_OUT, "Souhaitez-vous vraiment vous d\u00e9connecter de PayPal\u00a0?");
        f975a.put(bO.CONFIRM_SEND_PAYMENT, "Envoyer le paiement");
        f975a.put(bO.CONSENT_AGREEMENT_AGREE, "Accepter");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Date de cr\u00e9ation du compte");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "\u00c9tat du compte");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Type de compte");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adresse");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Tranche d\u2019\u00e2ge");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Date de naissance");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Adresse email");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Nom complet");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Sexe");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Langue");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Pays");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "T\u00e9l\u00e9phone");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Fuseau horaire");
        f975a.put(bO.CONSENT_AGREEMENT_ATTRIBUTES, "Partager les informations suivantes\u00a0: %s.");
        f975a.put(bO.CONSENT_AGREEMENT_INTRO, "%s vous demande de\u00a0:");
        f975a.put(bO.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Autoriser les d\u00e9bits</a> pour les futurs achats chez %2$s pay\u00e9s avec PayPal. Vous donnez pour instruction \u00e0 PayPal de payer tous les montants demand\u00e9s par %3$s.");
        f975a.put(bO.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Accepter le <a href='%2$s'>r\u00e8glement sur le respect de la vie priv\u00e9e</a> et les <a href='%3$s'>conditions d\u2019utilisation</a> de %1$s .");
        f975a.put(bO.CONSENT_AGREEMENT_TITLE, "Accepter");
        f975a.put(bO.EMAIL, "Email");
        f975a.put(bO.ENVIRONMENT_MOCK_DATA, "Mock Data");
        f975a.put(bO.ENVIRONMENT_SANDBOX, "Environnement de test");
        f975a.put(bO.EXPIRES_ON_DATE, "Date d\u2019expiration");
        f975a.put(bO.FORGOT_PASSWORD, "Mot de passe oubli\u00e9\u00a0?");
        f975a.put(bO.FROM_ACCOUNT, "De");
        f975a.put(bO.FUTURE_PAYMENT_METHOD_QUESTION, "Comment souhaitez-vous approvisionner les futurs paiements \u00e0 %1$s\u00a0?");
        f975a.put(bO.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Autorisation pour les futurs paiements</strong></h1><p>Votre source d\u2019approvisionnement par d\u00e9faut sera utilis\u00e9e pour payer les futurs paiements PayPal chez ce marchand.</p><p>Pour annuler cette autorisation, connectez-vous \u00e0 votre compte PayPal et acc\u00e9dez \u00e0 <strong>Pr\u00e9f\u00e9rences</strong> &gt; <strong>Mes param\u00e8tres</strong> &gt; <strong>Connexion avec PayPal</strong> et supprimez ce marchand de la liste.</p><p>L\u2019article Paiement r\u00e9current des <a href='%s'>Conditions d\u2019utilisation de PayPal</a> s\u2019appliquera.</p><p>Pour s\u2019assurer que votre compte PayPal pourra \u00eatre d\u00e9bit\u00e9 \u00e0 l\u2019avenir, cette application peut simuler une petite transaction test sans transfert d\u2019argent.</p>");
        f975a.put(bO.INTERNAL_ERROR, "Erreur interne");
        f975a.put(bO.JAPANESE_COMPLIANCE_AGREEMENT, "<p>En cliquant sur le bouton ci-dessous, j\u2019accepte les <a href='%1$s'>Conditions d\u2019utilisation de PayPal</a> et d\u00e9clare \u00eatre en conformit\u00e9 avec les lois et r\u00e9glementations japonaises, notamment les sanctions li\u00e9es aux paiements vers la Cor\u00e9e-du-Nord et l\u2019Iran conform\u00e9ment au <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> pour effectuer cette transaction.</p>");
        f975a.put(bO.LOG_IN, "Connexion");
        f975a.put(bO.LOG_IN_TO_PAYPAL, "Connexion avec PayPal");
        f975a.put(bO.LOG_OUT_BUTTON, "D\u00e9connexion");
        f975a.put(bO.LOG_OUT, "D\u00e9connexion");
        f975a.put(bO.OK, "OK");
        f975a.put(bO.PASSWORD, "Mot de passe");
        f975a.put(bO.PAY_AFTER_DELIVERY, "Paiement apr\u00e8s Livraison");
        f975a.put(bO.PAY_WITH, "Payer par");
        f975a.put(bO.PAY_WITH_CARD, "Payer par carte");
        f975a.put(bO.PAYPAL_BALANCE, "Solde PayPal");
        f975a.put(bO.PHONE, "T\u00e9l\u00e9phone");
        f975a.put(bO.PIN, "Code d\u2019acc\u00e8s");
        f975a.put(bO.PREFERRED_PAYMENT_METHOD, "Mode de paiement principal");
        f975a.put(bO.PRIVACY, "PayPal garantit le <a href='%s'>respect de votre vie priv\u00e9e</a> et prot\u00e8ge vos informations financi\u00e8res.");
        f975a.put(bO.PROCESSING, "En cours de traitement");
        f975a.put(bO.REMEMBER_CARD, "M\u00e9moriser la carte");
        f975a.put(bO.SAVINGS_ACCOUNT_FOR_INSTITUTION, "\u00c9pargne");
        f975a.put(bO.SERVER_PROBLEM, "Un probl\u00e8me est survenu lors de la communication avec les serveurs PayPal. Merci de recommencer.");
        f975a.put(bO.SESSION_EXPIRED_MESSAGE, "Merci de vous reconnecter \u00e0 PayPal.");
        f975a.put(bO.SESSION_EXPIRED_TITLE, "La session a expir\u00e9");
        f975a.put(bO.SHIPPING_ADDRESS, "Adresse de livraison\u00a0");
        f975a.put(bO.STAY_LOGGED_IN, "Rester connect\u00e9");
        f975a.put(bO.SYSTEM_ERROR_WITH_CODE, "Erreur syst\u00e8me (%s). R\u00e9essayez ult\u00e9rieurement.");
        f975a.put(bO.TRY_AGAIN, "R\u00e9essayer");
        f975a.put(bO.TWO_FA_REQUIRED_ERROR, "Nous ne pouvons pas vous connecter car votre compte fait l\u2019objet d\u2019une authentification \u00e0 deux facteurs.");
        f975a.put(bO.UNAUTHORIZED_DEVICE_MESSAGE, "Vous ne pouvez pas effectuer de paiements \u00e0 partir de cet appareil.");
        f975a.put(bO.UNAUTHORIZED_DEVICE_TITLE, "Appareil non autoris\u00e9");
        f975a.put(bO.UNAUTHORIZED_MERCHANT_MESSAGE, "Les paiements \u00e0 ce marchand ne sont pas autoris\u00e9s (identifiant client incorrect).");
        f975a.put(bO.UNAUTHORIZED_MERCHANT_TITLE, "Marchand incorrect");
        f975a.put(bO.UNEXPECTED_PAYMENT_FLOW, "Un probl\u00e8me est survenu lors du traitement de votre paiement. R\u00e9essayez.");
        f975a.put(bO.UNKNOWN_FUNDING_SOURCE, "Source non reconnue");
        f975a.put(bO.WE_ARE_SORRY, "D\u00e9sol\u00e9");
        f975a.put(bO.YOUR_ORDER, "Votre commande");
        f975a.put(bO.CLEAR_CC_ALERT_TITLE, "Effacer la carte\u00a0?");
        f975a.put(bO.CONSENT_FAILED_ALERT_TITLE, "\u00c9chec de l\u2019autorisation");
        f975a.put(bO.CONNECTION_FAILED_TITLE, "\u00c9chec de la connexion");
        f975a.put(bO.LOGIN_FAILED_ALERT_TITLE, "\u00c9chec de la connexion");
        f975a.put(bO.LOGIN_WITH_EMAIL, "Connexion par mot de passe");
        f975a.put(bO.LOGIN_WITH_PHONE, "Connexion par code d\u2019acc\u00e8s");
        f975a.put(bO.ONE_MOMENT, "Un instant\u2026");
        f975a.put(bO.PAY_FAILED_ALERT_TITLE, "\u00c9chec du paiement");
        f975a.put(bO.SCAN_CARD_ICON_DESCRIPTION, "Scanner");
        f975a.put(bO.VIA_LABEL, "Via");
        f975a.put(bO.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Erreur syst\u00e8me. R\u00e9essayez ult\u00e9rieurement.");
        f976b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Autorisation pour les futurs paiements</strong></h1><p>Pour nous assurer que votre compte PayPal pourra \u00eatre d\u00e9bit\u00e9, cette application peut simuler une petite transaction test sans transfert d\u2019argent.</p><p>Votre solde PayPal ou votre carte principale sera utilis\u00e9 pour payer des achats PayPal.</p><p>Pour annuler cette autorisation, connectez-vous \u00e0 votre compte PayPal et acc\u00e9dez \u00e0 <strong>Pr\u00e9f\u00e9rences</strong> &gt; <strong>Mes param\u00e8tres</strong> &gt; <strong>Connexion avec PayPal</strong> et supprimez ce marchand de la liste.</p>");
        f976b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Pr\u00e9approuver les futurs paiements effectu\u00e9s depuis votre <a href='%1$s'>compte PayPal</a>.");
        f976b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Autoriser les d\u00e9bits</a> pour les futurs achats chez %2$s pay\u00e9s avec PayPal. Vous donnez pour instruction \u00e0 PayPal de payer tous les montants demand\u00e9s par %3$s.</p><p>Consultez l\u2019article <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Paiements r\u00e9currents et autorisation de facturation PayPal</a> pour en savoir plus.</p>");
        f976b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autorisation pour les futurs paiements</strong></h1><p>Pour nous assurer que votre compte PayPal pourra \u00eatre d\u00e9bit\u00e9, cette application peut simuler une petite transaction test sans transfert d\u2019argent.</p><p>Votre mode de paiement par d\u00e9faut sera utilis\u00e9 pour payer vos achats PayPal. </p><p>Pour annuler cette autorisation, connectez-vous \u00e0 votre compte PayPal, acc\u00e9dez \u00e0 <strong>Pr\u00e9f\u00e9rences</strong> &gt; <strong>Param\u00e8tres de mon compte</strong> &gt; <strong>Connexion avec PayPal</strong> et supprimez ce marchand de la liste.</p><p>Consultez l\u2019article Paiements pr\u00e9approuv\u00e9s des <a href='%s'>Conditions d\u2019utilisation de PayPal</a> pour en savoir plus.</p>");
        f976b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Autorisation pour les futurs paiements</strong></h1><p>Pour nous assurer que votre compte PayPal pourra \u00eatre d\u00e9bit\u00e9, cette application peut simuler une petite transaction test sans transfert d\u2019argent.</p><p>Votre mode de paiement par d\u00e9faut sera utilis\u00e9 pour payer vos achats PayPal. </p><p>Pour annuler cette autorisation, connectez-vous \u00e0 votre compte PayPal, acc\u00e9dez \u00e0 <strong>Pr\u00e9f\u00e9rences</strong> &gt; <strong>Param\u00e8tres de mon compte</strong> &gt; <strong>Connexion avec PayPal</strong> et supprimez ce marchand de la liste.</p><p>Consultez l\u2019article Paiements pr\u00e9approuv\u00e9s des <a href='%s'>Conditions d\u2019utilisation de PayPal</a> pour en savoir plus.</p>");
        f976b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Autorisation pour les futurs paiements</strong></h1><p>Pour s\u2019assurer que votre compte PayPal pourra \u00eatre d\u00e9bit\u00e9, cette application peut simuler une petite transaction test sans transfert d\u2019argent.</p><p>Votre mode de paiement par d\u00e9faut (solde PayPal, compte bancaire li\u00e9 ou carte bancaire, dans cet ordre) sera utilis\u00e9 pour payer des achats PayPal. Si votre mode de paiement par d\u00e9faut n\u2019est pas suffisamment approvisionn\u00e9 pour couvrir l\u2019achat, votre banque ou l\u2019\u00e9metteur de votre carte peuvent vous d\u00e9biter des frais.</p><p>Pour annuler cette autorisation, connectez-vous \u00e0 votre compte PayPal et acc\u00e9dez \u00e0 <strong>Pr\u00e9f\u00e9rences</strong>, puis cliquez sur <strong>Mes param\u00e8tres</strong> et <strong>Modifier</strong> \u00e0 c\u00f4t\u00e9 de Connexion avec PayPal.</p>");
        f976b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Autorisation pour les futurs paiements</strong></h1><p>Pour nous assurer que votre compte PayPal pourra \u00eatre d\u00e9bit\u00e9, cette application peut simuler une petite transaction test sans transfert d\u2019argent.</p><p>Votre solde PayPal ou votre carte principale sera utilis\u00e9 pour payer des achats PayPal.</p><p>Pour annuler cette autorisation, connectez-vous \u00e0 votre compte PayPal et acc\u00e9dez \u00e0 <strong>Pr\u00e9f\u00e9rences</strong> &gt; <strong>Mes param\u00e8tres</strong> &gt; <strong>Connexion avec PayPal</strong> et supprimez ce marchand de la liste.</p>");
        f976b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Autorisation pour les futurs paiements</strong></h1><p>PayPal utilisera votre solde PayPal en priorit\u00e9 pour payer les achats. S\u2019il ne couvre pas le montant total de la transaction, votre cr\u00e9dit PayPal, votre carte bancaire et/ou un virement diff\u00e9r\u00e9 seront utilis\u00e9s dans cet ordre.</p><p>Pour annuler cette autorisation, acc\u00e9dez \u00e0 www.paypal.com, s\u00e9lectionnez <strong>Pr\u00e9f\u00e9rences</strong> &gt; <strong>Mes param\u00e8tres</strong> &gt; <strong>Connexion avec PayPal</strong> et supprimez ce marchand de la liste.</p><p>Une faible autorisation de paiement peut \u00eatre requise pour nous assurer que votre compte PayPal peut d\u00e9sormais \u00eatre d\u00e9bit\u00e9. Cette autorisation sera annul\u00e9e et vous ne serez pas d\u00e9bit\u00e9.</p>");
        f976b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Autorisation pour les futurs paiements</strong></h1><p>Pour s\u2019assurer que votre compte PayPal pourra \u00eatre d\u00e9bit\u00e9, cette application peut simuler une petite transaction test sans transfert d\u2019argent.</p><p>Votre mode de paiement par d\u00e9faut sera utilis\u00e9 pour payer les achats PayPal. </p><p>Pour annuler cette autorisation, connectez-vous \u00e0 votre compte PayPal, acc\u00e9dez \u00e0 <strong>Pr\u00e9f\u00e9rences</strong> &gt; <strong>Param\u00e8tres</strong> &gt; <strong>Connexion avec PayPal</strong> et supprimez ce marchand de la liste.</p>");
        f976b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Autorisation pour les futurs paiements</strong></h1><p>Pour nous assurer que votre compte PayPal pourra \u00eatre d\u00e9bit\u00e9, cette application peut simuler une petite transaction test sans transfert d\u2019argent.</p><p>Votre mode de paiement par d\u00e9faut sera utilis\u00e9 pour payer vos achats PayPal. </p><p>Pour annuler cette autorisation, connectez-vous \u00e0 votre compte PayPal, acc\u00e9dez \u00e0 <strong>Pr\u00e9f\u00e9rences</strong> &gt; <strong>Param\u00e8tres de mon compte</strong> &gt; <strong>Connexion avec PayPal</strong> et supprimez ce marchand de la liste.</p><p>Consultez l\u2019article Paiements pr\u00e9approuv\u00e9s des <a href='%s'>Conditions d\u2019utilisation de PayPal</a> pour en savoir plus.</p>");
        f976b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Autoriser les d\u00e9bits</a> pour les futurs achats chez %2$s pay\u00e9s avec PayPal. Vous donnez pour instruction \u00e0 PayPal de payer tous les montants demand\u00e9s par %3$s.</p><p>Consultez l\u2019article <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Paiements r\u00e9currents et autorisation de facturation PayPal</a> pour en savoir plus.</p>");
        f977c.put("INTERNAL_SERVICE_ERROR", "Erreur syst\u00e8me. R\u00e9essayez ult\u00e9rieurement.");
        f977c.put("EXPIRED_CREDIT_CARD", "La carte a expir\u00e9");
        f977c.put("EXPIRED_CREDIT_CARD_TOKEN", "Les informations de cette carte ne sont plus enregistr\u00e9es.\nMerci de les renvoyer.");
        f977c.put("INVALID_ACCOUNT_NUMBER", "Ce num\u00e9ro de compte n\u2019existe pas.");
        f977c.put("INVALID_RESOURCE_ID", "Erreur syst\u00e8me. R\u00e9essayez ult\u00e9rieurement.");
        f977c.put("DUPLICATE_REQUEST_ID", "Erreur syst\u00e8me. R\u00e9essayez ult\u00e9rieurement.");
        f977c.put("TRANSACTION_LIMIT_EXCEEDED", "Le montant d\u00e9passe la limite autoris\u00e9e.");
        f977c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Le remboursement demand\u00e9 d\u00e9passe le montant de la transaction d\u2019origine.");
        f977c.put("REFUND_TIME_LIMIT_EXCEEDED", "Cette transaction est trop ancienne pour \u00eatre rembours\u00e9e.");
        f977c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Cette transaction a d\u00e9j\u00e0 \u00e9t\u00e9 partiellement rembours\u00e9e.");
        f977c.put("TRANSACTION_ALREADY_REFUNDED", "Cette transaction a d\u00e9j\u00e0 \u00e9t\u00e9 rembours\u00e9e.");
        f977c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Le montant d\u00e9passe la limite autoris\u00e9e.");
        f977c.put("AUTHORIZATION_ALREADY_COMPLETED", "Cette autorisation a d\u00e9j\u00e0 \u00e9t\u00e9 accord\u00e9e.");
        f977c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Seule l\u2019autorisation initiale peut \u00eatre accord\u00e9e de nouveau, pas une nouvelle autorisation.");
        f977c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Une nouvelle autorisation ne peut pas \u00eatre accord\u00e9e pendant la p\u00e9riode de validit\u00e9.");
        f977c.put("TOO_MANY_REAUTHORIZATIONS", "Plus aucune nouvelle autorisation ne peut \u00eatre accord\u00e9e pour cette autorisation.");
        f977c.put("PERMISSION_DENIED", "Pas de droit d\u2019acc\u00e8s pour l\u2019op\u00e9ration demand\u00e9e.");
        f977c.put("AUTHORIZATION_VOIDED", "L\u2019autorisation a \u00e9t\u00e9 annul\u00e9e.");
        f977c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "L\u2019identifiant d\u2019autorisation demand\u00e9 n\u2019existe pas.");
        f977c.put("VALIDATION_ERROR", "Les informations de paiement sont incorrectes. Corrigez-les et renvoyez-les.");
        f977c.put("CREDIT_CARD_REFUSED", "La carte a \u00e9t\u00e9 rejet\u00e9e.");
        f977c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Les informations relatives \u00e0 la carte sont incorrectes. Corrigez-les et renvoyez-les.");
        f977c.put("PAYEE_ACCOUNT_RESTRICTED", "Ce vendeur ne peut pas recevoir de paiements pour le moment.");
        f977c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Le payeur n\u2019a pas approuv\u00e9 le paiement.");
        f977c.put("INVALID_PAYER_ID", "Erreur syst\u00e8me (identifiant de payeur incorrect). R\u00e9essayez ult\u00e9rieurement.");
        f977c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Ce vendeur ne peut pas recevoir de paiements pour le moment.");
        f977c.put("PAYMENT_APPROVAL_EXPIRED", "L\u2019approbation du paiement a expir\u00e9.");
        f977c.put("PAYMENT_EXPIRED", "Le paiement a expir\u00e9.");
        f977c.put("DATA_RETRIEVAL", "Erreur syst\u00e8me. R\u00e9essayez ult\u00e9rieurement.");
        f977c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Le compte du b\u00e9n\u00e9ficiaire n\u2019a pas d\u2019adresse email confirm\u00e9e.");
        f977c.put("PAYMENT_STATE_INVALID", "Cette demande n\u2019est pas valable, en raison de l\u2019\u00e9tat actuel du paiement.");
        f977c.put("TRANSACTION_REFUSED", "La transaction a \u00e9t\u00e9 refus\u00e9e.");
        f977c.put("AMOUNT_MISMATCH", "Le total des montants des objets du panier ne correspond pas au montant de la vente.");
        f977c.put("CURRENCY_NOT_ALLOWED", "Cette devise n\u2019est pas prise en charge par PayPal actuellement.");
        f977c.put("CURRENCY_MISMATCH", "La devise de la collecte doit \u00eatre la m\u00eame que celle de l\u2019autorisation.");
        f977c.put("AUTHORIZATION_EXPIRED", "L\u2019autorisation a expir\u00e9.");
        f977c.put("INVALID_ARGUMENT", "Transaction refus\u00e9e en raison d\u2019un argument incorrect");
        f977c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Impossible d\u2019acc\u00e9der aux informations de carte enregistr\u00e9es.");
        f977c.put("CARD_TOKEN_PAYER_MISMATCH", "Impossible d\u2019acc\u00e9der aux informations de carte enregistr\u00e9es.");
        f977c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "L\u2019\u00e9tat de l\u2019autorisation ne permet pas son annulation.");
        f977c.put("REQUIRED_SCOPE_MISSING", "Erreur syst\u00e8me. R\u00e9essayez ult\u00e9rieurement.");
        f977c.put("UNAUTHORIZED_PAYMENT", "Ce marchand n\u2019accepte pas les paiements de ce type.");
        f977c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Devise non accept\u00e9e pour le type de carte.");
        f977c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Ce type de carte n\u2019est pas pris en charge.");
        f977c.put("INSUFFICIENT_FUNDS", "L\u2019acheteur ne peut pas payer, provision insuffisante.");
        f977c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Les pr\u00e9f\u00e9rences du marchand sont r\u00e9gl\u00e9es pour rejeter automatiquement certaines transactions.");
        f977c.put("INVALID_FACILITATOR_CONFIGURATION", "Cette transaction ne peut pas \u00eatre trait\u00e9e car la configuration du facilitateur est incorrecte.");
        f977c.put("ORDER_ALREADY_COMPLETED", "La commande a d\u00e9j\u00e0 \u00e9t\u00e9 annul\u00e9e, est termin\u00e9e ou a expir\u00e9.");
        f977c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Le nombre maximum d\u2019autorisations pour la commande a \u00e9t\u00e9 atteint.");
        f977c.put("ORDER_VOIDED", "La commande a \u00e9t\u00e9 annul\u00e9e.");
        f977c.put("ORDER_CANNOT_BE_VOIDED", "La commande ne peut pas \u00eatre annul\u00e9e en raison de son \u00e9tat.");
        f977c.put("ADDRESS_ADDITION_ERROR", "Erreur lors de l\u2019ajout de l\u2019adresse de livraison au compte PayPal.");
        f977c.put("INVALID_SHIPPING_ADDRESS", "L\u2019adresse de livraison fournie n\u2019est pas correcte.");
        f977c.put("DUPLICATE_TRANSACTION", "Transaction en double.");
        f977c.put("AUTH_RC_RISK_FAILURE", "Rejet\u00e9 en raison d\u2019un risque trop \u00e9lev\u00e9.");
        f977c.put("AUTH_RC_OFAC_BLOCKED_IP", "Client non autoris\u00e9.");
        f977c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Client non autoris\u00e9.");
        f977c.put("invalid_user", "Nom d\u2019utilisateur/mot de passe incorrect. Merci de recommencer.");
        f977c.put("invalid_request", "Une erreur s\u2019est produite.");
        f977c.put("unauthorized_client", "Demande non autoris\u00e9e.");
        f977c.put("access_denied", "Demande non autoris\u00e9e.");
        f977c.put("unsupported_response_type", "Une erreur s\u2019est produite.");
        f977c.put("invalid_scope", "Demande non autoris\u00e9e.");
        f977c.put("server_error", "Erreur syst\u00e8me. R\u00e9essayez ult\u00e9rieurement.");
        f977c.put("temporarily_unavailable", "Erreur syst\u00e8me. R\u00e9essayez ult\u00e9rieurement.");
    }

    public final String m880a() {
        return "fr";
    }

    public final /* synthetic */ String m881a(Enum enumR, String str) {
        bO bOVar = (bO) enumR;
        String str2 = bOVar.toString() + "|" + str;
        return f976b.containsKey(str2) ? (String) f976b.get(str2) : (String) f975a.get(bOVar);
    }

    public final String m882a(String str) {
        return (String) f977c.get(str);
    }
}
