package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

public final class aF implements at {
    private static Map f981a;
    private static Map f982b;
    private static Map f983c;

    static {
        f981a = new HashMap();
        f982b = new HashMap();
        f983c = new HashMap();
    }

    public aF() {
        f981a.put(bO.AND_OTHER_FUNDING_SOURCES, "e altri");
        f981a.put(bO.AUTHENTICATING, "Autenticazione\u2026");
        f981a.put(bO.BACK_BUTTON, "Prec.");
        f981a.put(bO.BACKUP_FUNDING_SOURCE, "Di riserva");
        f981a.put(bO.CANCEL, "Annulla");
        f981a.put(bO.CARDTYPE_AMERICANEXPRESS, "American Express");
        f981a.put(bO.CARDTYPE_CARTAAURA, "Carta Aura");
        f981a.put(bO.CARDTYPE_CARTEAURORE, "Carta Aurore");
        f981a.put(bO.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f981a.put(bO.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f981a.put(bO.CARDTYPE_COFINOGA, "Cofinoga");
        f981a.put(bO.CARDTYPE_DELTA, "Delta");
        f981a.put(bO.CARDTYPE_DISCOVER, "Discover");
        f981a.put(bO.CARDTYPE_ELECTRON, "Electron");
        f981a.put(bO.CARDTYPE_JCB, "JCB");
        f981a.put(bO.CARDTYPE_MAESTRO, "Maestro");
        f981a.put(bO.CARDTYPE_MASTERCARD, "MasterCard");
        f981a.put(bO.CARDTYPE_POSTEPAY, "Postepay");
        f981a.put(bO.CARDTYPE_4ETOILES, "4 \u00e9toiles");
        f981a.put(bO.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f981a.put(bO.CARDTYPE_VISA, "Visa");
        f981a.put(bO.CHANGE_PAYMENT_METHOD, "Modifica metodo di pagamento");
        f981a.put(bO.CHECKING_ACCOUNT_FOR_INSTITUTION, "Conto corrente");
        f981a.put(bO.CHECKING_DEVICE, "Controllo dispositivo\u2026");
        f981a.put(bO.CLEAR_CREDIT_CARD_INFO, "Rimuovi dati della carta");
        f981a.put(bO.CONFIRM, "Conferma");
        f981a.put(bO.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Rimuovere i dati della carta?");
        f981a.put(bO.CONFIRM_CHARGE_CREDIT_CARD, "Addebita importo sulla carta");
        f981a.put(bO.CONFIRM_LOG_OUT, "Vuoi uscire da PayPal?");
        f981a.put(bO.CONFIRM_SEND_PAYMENT, "Invia pagamento");
        f981a.put(bO.CONSENT_AGREEMENT_AGREE, "Accetta");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Data creazione conto");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Stato del conto");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Tipo di conto");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Indirizzo");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Fascia di et\u00e0");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Data di nascita");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Indirizzo email");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Nome e cognome");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Sesso");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Lingua");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Locale");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefono");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Fuso orario");
        f981a.put(bO.CONSENT_AGREEMENT_ATTRIBUTES, "Condividi il seguente: %s.");
        f981a.put(bO.CONSENT_AGREEMENT_INTRO, "%s ti chiede di:");
        f981a.put(bO.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Autorizzare l\u2019addebito</a> degli acquisti futuri effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.");
        f981a.put(bO.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Accettare l\u2019<a href='%2$s'> </a>Informativa sulla privacy<a href='%3$s'> e le </a>Condizioni d\u2019uso di %1$s.");
        f981a.put(bO.CONSENT_AGREEMENT_TITLE, "Consenso");
        f981a.put(bO.EMAIL, "Email");
        f981a.put(bO.ENVIRONMENT_MOCK_DATA, "Dati di esempio");
        f981a.put(bO.ENVIRONMENT_SANDBOX, "Sandbox");
        f981a.put(bO.EXPIRES_ON_DATE, "Scadenza");
        f981a.put(bO.FORGOT_PASSWORD, "Password dimenticata?");
        f981a.put(bO.FROM_ACCOUNT, "Da");
        f981a.put(bO.FUTURE_PAYMENT_METHOD_QUESTION, "Come vuoi pagare i prossimi acquisti su %1$s?");
        f981a.put(bO.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Autorizzazione di pagamenti futuri</strong></h1><p>Gli importi dei pagamenti automatici effettuati con PayPal da questa app verranno prelevati dal tuo metodo di pagamento predefinito.</p><p>Per annullare l\u2019autorizzazione, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p><p>Si applica la sezione Pagamenti automatici delle <a href='%s'>Condizioni d\u2019uso PayPal</a>.</p><p>Per verificare il funzionamento dell\u2019addebito dei pagamenti automatici sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p>");
        f981a.put(bO.INTERNAL_ERROR, "Errore interno");
        f981a.put(bO.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Cliccando il pulsante di seguito, accetto le <a href='%1$s'>Condizioni d\u2019uso PayPal</a> e dichiaro di rispettare le leggi e normative del Giappone, tra cui le sanzioni previste per i pagamenti alla Corea del Nord e all\u2019Iran in base al <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> (Legge sugli scambi e sul commercio estero), per completare la transazione.</p>");
        f981a.put(bO.LOG_IN, "Accedi");
        f981a.put(bO.LOG_IN_TO_PAYPAL, "Log in con PayPal");
        f981a.put(bO.LOG_OUT_BUTTON, "Esci");
        f981a.put(bO.LOG_OUT, "Esci");
        f981a.put(bO.OK, "OK");
        f981a.put(bO.PASSWORD, "Password");
        f981a.put(bO.PAY_AFTER_DELIVERY, "Paga dopo la consegna");
        f981a.put(bO.PAY_WITH, "Paga con");
        f981a.put(bO.PAY_WITH_CARD, "Paga con una carta");
        f981a.put(bO.PAYPAL_BALANCE, "Saldo PayPal");
        f981a.put(bO.PHONE, "Telefono");
        f981a.put(bO.PIN, "PIN");
        f981a.put(bO.PREFERRED_PAYMENT_METHOD, "Metodo di pagamento preferito");
        f981a.put(bO.PRIVACY, "PayPal protegge la tua <a href='%s'>privacy</a> e i tuoi dati finanziari.");
        f981a.put(bO.PROCESSING, "Elaborazione in corso");
        f981a.put(bO.REMEMBER_CARD, "Ricorda dati carta");
        f981a.put(bO.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Conto corrente");
        f981a.put(bO.SERVER_PROBLEM, "Si \u00e8 verificato un problema con i nostri server. Riprova.");
        f981a.put(bO.SESSION_EXPIRED_MESSAGE, "Ripeti l\u2019accesso a PayPal.");
        f981a.put(bO.SESSION_EXPIRED_TITLE, "Sessione scaduta");
        f981a.put(bO.SHIPPING_ADDRESS, "Indirizzo di spedizione");
        f981a.put(bO.STAY_LOGGED_IN, "Rimani collegato");
        f981a.put(bO.SYSTEM_ERROR_WITH_CODE, "Errore di sistema (%s). Riprova pi\u00f9 tardi.");
        f981a.put(bO.TRY_AGAIN, "Riprova");
        f981a.put(bO.TWO_FA_REQUIRED_ERROR, "Impossibile effettuare l\u2019accesso perch\u00e9 sul tuo conto \u00e8 attivata la doppia autenticazione.");
        f981a.put(bO.UNAUTHORIZED_DEVICE_MESSAGE, "Pagamenti da questo dispositivo non consentiti.");
        f981a.put(bO.UNAUTHORIZED_DEVICE_TITLE, "Dispositivo non autorizzato");
        f981a.put(bO.UNAUTHORIZED_MERCHANT_MESSAGE, "I pagamenti a questo venditore non sono consentiti (clientId non valido).");
        f981a.put(bO.UNAUTHORIZED_MERCHANT_TITLE, "Sito non valido");
        f981a.put(bO.UNEXPECTED_PAYMENT_FLOW, "Si \u00e8 verificato un problema durante l\u2019elaborazione del pagamento. Riprova.");
        f981a.put(bO.UNKNOWN_FUNDING_SOURCE, "Metodo non riconosciuto");
        f981a.put(bO.WE_ARE_SORRY, "Spiacenti");
        f981a.put(bO.YOUR_ORDER, "Il tuo ordine");
        f981a.put(bO.CLEAR_CC_ALERT_TITLE, "Rimuovere la carta?");
        f981a.put(bO.CONSENT_FAILED_ALERT_TITLE, "Consenso non riuscito");
        f981a.put(bO.CONNECTION_FAILED_TITLE, "Connessione non riuscita");
        f981a.put(bO.LOGIN_FAILED_ALERT_TITLE, "Accesso non riuscito");
        f981a.put(bO.LOGIN_WITH_EMAIL, "Accedi con la password");
        f981a.put(bO.LOGIN_WITH_PHONE, "Accedi con il PIN");
        f981a.put(bO.ONE_MOMENT, "Attendi\u2026");
        f981a.put(bO.PAY_FAILED_ALERT_TITLE, "Pagamento non riuscito");
        f981a.put(bO.SCAN_CARD_ICON_DESCRIPTION, "Scansione");
        f981a.put(bO.VIA_LABEL, "tramite");
        f981a.put(bO.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Errore di sistema. Riprova pi\u00f9 tardi.");
        f982b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Autorizzazione di pagamenti futuri</strong></h1><p>Per verificare la possibilit\u00e0 di addebitare i pagamenti automatici sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Per pagare gli acquisti con PayPal verr\u00e0 usato il tuo saldo PayPal o la tua carta di credito o di debito (bancomat) principale.</p><p>Per annullare l\u2019autorizzazione, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p>");
        f982b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Autorizza i pagamenti automatici dal tuo <a href='%1$s'>conto PayPal</a>.");
        f982b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Autorizzare l\u2019addebito</a> degli acquisti futuri effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.</p><p>Vedi <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Pagamenti automatici e Contratto di addebito automatico PayPal</a> per maggiori informazioni.</p>");
        f982b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autorizzazione di pagamenti futuri</strong></h1><p>Per verificare la possibilit\u00e0 di addebitare i pagamenti automatici sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verr\u00e0 usato per pagare gli acquisti con PayPal.</p><p>Per annullare l\u2019autorizzazione, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p><p>Vedi la sezione \u201cPagamenti automatici\u201d delle <a href='%s'>Condizioni d\u2019uso PayPal</a> per maggiori informazioni.</p>");
        f982b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Autorizzazione di pagamenti futuri</strong></h1><p>Per verificare la possibilit\u00e0 di addebitare i pagamenti automatici sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verr\u00e0 usato per pagare gli acquisti con PayPal.</p><p>Per annullare l\u2019autorizzazione, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p><p>Vedi la sezione \u201cPagamenti automatici\u201d delle <a href='%s'>Condizioni d\u2019uso PayPal</a> per maggiori informazioni.</p>");
        f982b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Autorizzazione di pagamenti futuri</strong></h1><p>Per verificare la possibilit\u00e0 di addebitare i pagamenti automatici sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito (il saldo PayPal, il conto bancario, la carta di credito o di debito, in quest\u2019ordine) verr\u00e0 usato per pagare gli acquisti con PayPal. Se sul tuo metodo di pagamento preferito non \u00e8 presente denaro sufficiente per l\u2019acquisto, la banca o la societ\u00e0 emittente della carta potrebbe addebitarti una tariffa.</p><p>Per annullare l\u2019autorizzazione, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong>, quindi clicca <strong>Impostazioni</strong> e <strong>Modifica</strong> accanto a \u201cLog in con PayPal\u201d.</p>");
        f982b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Autorizzazione di pagamenti futuri</strong></h1><p>Per verificare la possibilit\u00e0 di addebitare i pagamenti automatici sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Per pagare gli acquisti con PayPal verr\u00e0 usato il tuo saldo PayPal o la tua carta di credito o di debito (bancomat) principale.</p><p>Per annullare l\u2019autorizzazione, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p>");
        f982b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Autorizzazione di pagamenti futuri</strong></h1><p>Il tuo saldo PayPal verr\u00e0 usato come prima opzione per pagare i tuoi acquisti. Se non \u00e8 sufficiente, verranno usati (nell\u2019ordine): il conto bancario, PayPal Credit, la carta di debito (bancomat), la carta di credito, gli eCheck.</p><p>Per annullare l\u2019autorizzazione, visita il sito www.paypal.it e clicca <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante dall\u2019elenco.</p><p>Potrebbe essere richiesta l\u2019autorizzazione di un piccolo pagamento per verificare la possibilit\u00e0 di addebitare i pagamenti automatici sul tuo conto PayPal. L\u2019autorizzazione verr\u00e0 annullata e non ti verr\u00e0 addebitato alcun importo.</p>");
        f982b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Autorizzazione di pagamenti futuri</strong></h1><p>Per verificare la possibilit\u00e0 di addebitare i pagamenti automatici sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verr\u00e0 usato per pagare gli acquisti con PayPal.</p><p>Per annullare l\u2019autorizzazione, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p>");
        f982b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Autorizzazione di pagamenti futuri</strong></h1><p>Per verificare la possibilit\u00e0 di addebitare i pagamenti automatici sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verr\u00e0 usato per pagare gli acquisti con PayPal.</p><p>Per annullare l\u2019autorizzazione, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p><p>Vedi la sezione \u201cPagamenti automatici\u201d delle <a href='%s'>Condizioni d\u2019uso PayPal</a> per maggiori informazioni.</p>");
        f982b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Autorizzare l\u2019addebito</a> degli acquisti futuri effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.</p><p>Vedi <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Pagamenti automatici e Contratto di addebito automatico PayPal</a> per maggiori informazioni.</p>");
        f983c.put("INTERNAL_SERVICE_ERROR", "Errore di sistema. Riprova pi\u00f9 tardi.");
        f983c.put("EXPIRED_CREDIT_CARD", "La carta \u00e8 scaduta");
        f983c.put("EXPIRED_CREDIT_CARD_TOKEN", "I dati di questa carta non sono pi\u00f9 in archivio.\nInoltrali di nuovo.");
        f983c.put("INVALID_ACCOUNT_NUMBER", "Il numero di conto non esiste.");
        f983c.put("INVALID_RESOURCE_ID", "Errore di sistema. Riprova pi\u00f9 tardi.");
        f983c.put("DUPLICATE_REQUEST_ID", "Errore di sistema. Riprova pi\u00f9 tardi.");
        f983c.put("TRANSACTION_LIMIT_EXCEEDED", "L\u2019importo supera il limite consentito.");
        f983c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Il rimborso richiesto supera l\u2019importo della transazione originale.");
        f983c.put("REFUND_TIME_LIMIT_EXCEEDED", "Questa transazione \u00e8 troppo datata per essere rimborsata.");
        f983c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "La transazione \u00e8 stata gi\u00e0 rimborsata parzialmente.");
        f983c.put("TRANSACTION_ALREADY_REFUNDED", "La transazione \u00e8 stata gi\u00e0 rimborsata.");
        f983c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "L\u2019importo supera il limite consentito.");
        f983c.put("AUTHORIZATION_ALREADY_COMPLETED", "L\u2019autorizzazione \u00e8 gi\u00e0 stata completata.");
        f983c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "\u00c8 possibile riautorizzare solo le autorizzazioni originali.");
        f983c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "La riautorizzazione non \u00e8 consentita nel periodo di validit\u00e0.");
        f983c.put("TOO_MANY_REAUTHORIZATIONS", "Per questa autorizzazione non sono pi\u00f9 consentite riautorizzazioni.");
        f983c.put("PERMISSION_DENIED", "L\u2019operazione richiesta non \u00e8 autorizzata.");
        f983c.put("AUTHORIZATION_VOIDED", "L\u2019autorizzazione \u00e8 stata annullata.");
        f983c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "L\u2019ID autorizzazione richiesto non esiste.");
        f983c.put("VALIDATION_ERROR", "I dati di pagamento non sono validi. Correggi i tuoi dati e riprova.");
        f983c.put("CREDIT_CARD_REFUSED", "Carta rifiutata.");
        f983c.put("CREDIT_CARD_CVV_CHECK_FAILED", "I dati della carta non sono validi. Correggi i tuoi dati e riprova.");
        f983c.put("PAYEE_ACCOUNT_RESTRICTED", "Questo venditore non pu\u00f2 ricevere pagamenti al momento.");
        f983c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "L\u2019acquirente non ha approvato il pagamento.");
        f983c.put("INVALID_PAYER_ID", "Errore di sistema (ID acquirente non valido). Riprova pi\u00f9 tardi.");
        f983c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Questo venditore non pu\u00f2 ricevere pagamenti al momento.");
        f983c.put("PAYMENT_APPROVAL_EXPIRED", "L\u2019approvazione del pagamento \u00e8 scaduta.");
        f983c.put("PAYMENT_EXPIRED", "Il pagamento \u00e8 scaduto.");
        f983c.put("DATA_RETRIEVAL", "Errore di sistema. Riprova pi\u00f9 tardi.");
        f983c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Il conto di beneficiario non ha un\u2019email confermata.");
        f983c.put("PAYMENT_STATE_INVALID", "Richiesta non valida nella provincia di pagamento.");
        f983c.put("TRANSACTION_REFUSED", "La transazione \u00e8 stata rifiutata.");
        f983c.put("AMOUNT_MISMATCH", "Il totale del carrello non corrisponde all\u2019importo delle vendite.");
        f983c.put("CURRENCY_NOT_ALLOWED", "Valuta non supportata da PayPal.");
        f983c.put("CURRENCY_MISMATCH", "La valuta di riscossione deve essere uguale a quella di autorizzazione.");
        f983c.put("AUTHORIZATION_EXPIRED", "L\u2019autorizzazione \u00e8 scaduta.");
        f983c.put("INVALID_ARGUMENT", "Transazione rifiutata per problemi tecnici");
        f983c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Impossibile accedere ai dati della carta in archivio.");
        f983c.put("CARD_TOKEN_PAYER_MISMATCH", "Impossibile accedere ai dati della carta in archivio.");
        f983c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "L\u2019autorizzazione \u00e8 in una provincia in cui non pu\u00f2 essere annullata.");
        f983c.put("REQUIRED_SCOPE_MISSING", "Errore di sistema. Riprova pi\u00f9 tardi.");
        f983c.put("UNAUTHORIZED_PAYMENT", "Il commerciante non accetta questo tipo di pagamenti.");
        f983c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valuta non supportata per il tipo di carta.");
        f983c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Tipo di carta non supportato.");
        f983c.put("INSUFFICIENT_FUNDS", "L\u2019acquirente non pu\u00f2 pagare per denaro insufficiente.");
        f983c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Le preferenze del commerciante sono impostate per rifiutare automaticamente determinate transazioni.");
        f983c.put("INVALID_FACILITATOR_CONFIGURATION", "Impossibile elaborare la transazione per configurazione non valida.");
        f983c.put("ORDER_ALREADY_COMPLETED", "L\u2019ordine \u00e8 stato gi\u00e0 annullato, \u00e8 scaduto o completato.");
        f983c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Il numero massimo di autorizzazioni consentite per l\u2019ordine \u00e8 stato raggiunto.");
        f983c.put("ORDER_VOIDED", "L\u2019ordine \u00e8 stato annullato.");
        f983c.put("ORDER_CANNOT_BE_VOIDED", "L\u2019ordine \u00e8 in uno stato che impedisce l\u2019annullamento.");
        f983c.put("ADDRESS_ADDITION_ERROR", "Si \u00e8 verificato un errore durante l\u2019aggiunta dell\u2019indirizzo di spedizione al conto PayPal.");
        f983c.put("INVALID_SHIPPING_ADDRESS", "L\u2019indirizzo di spedizione non \u00e8 valido.");
        f983c.put("DUPLICATE_TRANSACTION", "Transazione doppia");
        f983c.put("AUTH_RC_RISK_FAILURE", "Rifiutata per motivi di rischio.");
        f983c.put("AUTH_RC_OFAC_BLOCKED_IP", "Client non autorizzato.");
        f983c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Client non autorizzato.");
        f983c.put("invalid_user", "Email o password non corretta. Riprova.");
        f983c.put("invalid_request", "Si \u00e8 verificato un errore.");
        f983c.put("unauthorized_client", "Richiesta non autorizzata.");
        f983c.put("access_denied", "Richiesta non autorizzata.");
        f983c.put("unsupported_response_type", "Si \u00e8 verificato un errore.");
        f983c.put("invalid_scope", "Richiesta non autorizzata.");
        f983c.put("server_error", "Errore di sistema. Riprova pi\u00f9 tardi.");
        f983c.put("temporarily_unavailable", "Errore di sistema. Riprova pi\u00f9 tardi.");
    }

    public final String m886a() {
        return "it";
    }

    public final /* synthetic */ String m887a(Enum enumR, String str) {
        bO bOVar = (bO) enumR;
        String str2 = bOVar.toString() + "|" + str;
        return f982b.containsKey(str2) ? (String) f982b.get(str2) : (String) f981a.get(bOVar);
    }

    public final String m888a(String str) {
        return (String) f983c.get(str);
    }
}
