package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

public final class aJ implements at {
    private static Map f990a;
    private static Map f991b;
    private static Map f992c;

    static {
        f990a = new HashMap();
        f991b = new HashMap();
        f992c = new HashMap();
    }

    public aJ() {
        f990a.put(bO.AND_OTHER_FUNDING_SOURCES, "& lain");
        f990a.put(bO.AUTHENTICATING, "Mengesahkan");
        f990a.put(bO.BACK_BUTTON, "Undur");
        f990a.put(bO.BACKUP_FUNDING_SOURCE, "Sandaran");
        f990a.put(bO.CANCEL, "Batal");
        f990a.put(bO.CARDTYPE_AMERICANEXPRESS, "American Express");
        f990a.put(bO.CARDTYPE_CARTAAURA, "Carta Aura");
        f990a.put(bO.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f990a.put(bO.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f990a.put(bO.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f990a.put(bO.CARDTYPE_COFINOGA, "Cofinoga");
        f990a.put(bO.CARDTYPE_DELTA, "Delta");
        f990a.put(bO.CARDTYPE_DISCOVER, "Discover");
        f990a.put(bO.CARDTYPE_ELECTRON, "Electron");
        f990a.put(bO.CARDTYPE_JCB, "JCB");
        f990a.put(bO.CARDTYPE_MAESTRO, "Maestro");
        f990a.put(bO.CARDTYPE_MASTERCARD, "MasterCard");
        f990a.put(bO.CARDTYPE_POSTEPAY, "Postepay");
        f990a.put(bO.CARDTYPE_4ETOILES, "4 \u00e9toiles");
        f990a.put(bO.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f990a.put(bO.CARDTYPE_VISA, "Visa");
        f990a.put(bO.CHANGE_PAYMENT_METHOD, "Tukar Kaedah Pembayaran");
        f990a.put(bO.CHECKING_ACCOUNT_FOR_INSTITUTION, "Menyemak");
        f990a.put(bO.CHECKING_DEVICE, "Menyemak peranti ini\u2026");
        f990a.put(bO.CLEAR_CREDIT_CARD_INFO, "Kosongkan maklumat kad");
        f990a.put(bO.CONFIRM, "Sahkan");
        f990a.put(bO.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Adakah anda pasti anda ingin mengosongkan maklumat kad anda?");
        f990a.put(bO.CONFIRM_CHARGE_CREDIT_CARD, "Kad Caj");
        f990a.put(bO.CONFIRM_LOG_OUT, "Adakah anda pasti anda ingin log keluar dari PayPal?");
        f990a.put(bO.CONFIRM_SEND_PAYMENT, "Hantar Bayaran");
        f990a.put(bO.CONSENT_AGREEMENT_AGREE, "Setuju");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Tarikh Ciptaan Akaun");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Status Akaun");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Jenis Akaun");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Alamat");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Julat Umur");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Tarikh Lahir");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Alamat e-mel");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Nama Penuh");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Jantina");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Bahasa");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Tempatan");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Zon Waktu");
        f990a.put(bO.CONSENT_AGREEMENT_ATTRIBUTES, "Kongsi yang berikut: %s.");
        f990a.put(bO.CONSENT_AGREEMENT_INTRO, "%s meminta anda:");
        f990a.put(bO.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Benarkan caj</a> untuk pembelian %2$s pada masa depan yang dibayar melalui PayPal. Anda mengarahkan PayPal untuk membayar semua amaun yang diminta oleh %3$s.");
        f990a.put(bO.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Bersetuju dengan <a href='%2$s'>dasar privasi</a> dan <a href='%3$s'>perjanjian pengguna</a> %1$s.");
        f990a.put(bO.CONSENT_AGREEMENT_TITLE, "Persetujuan");
        f990a.put(bO.EMAIL, "E-mel");
        f990a.put(bO.ENVIRONMENT_MOCK_DATA, "Data Olok-olok");
        f990a.put(bO.ENVIRONMENT_SANDBOX, "Sandbox");
        f990a.put(bO.EXPIRES_ON_DATE, "Tamat tempoh");
        f990a.put(bO.FORGOT_PASSWORD, "Terlupa kata laluan?");
        f990a.put(bO.FROM_ACCOUNT, "Dari");
        f990a.put(bO.FUTURE_PAYMENT_METHOD_QUESTION, "Bagaimanakah anda ingin membiayai bayaran masa depan kepada %1$s?");
        f990a.put(bO.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Perjanjian Bayaran Masa Depan</strong></h1><p>Sumber pendanaan lalai anda akan digunakan untuk membuat bayaran PayPal masa depan daripada peniaga ini.</p><p>Untuk membatalkan perjanjian ini, log masuk ke akaun PayPal anda, pergi ke <strong>Profil</strong> &gt; <strong>Tetapan Saya</strong> &gt; <strong>Log Masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p><p>Bahagian Bayaran Berulang dalam <a href='%s'>Perjanjian Pengguna PayPal</a> akan diguna pakai.</p><p>Untuk memastikan bayaran boleh dibuat dengan akaun PayPal anda, aplikasi ini mungkin mensimulasikan transaksi ujian kecil, tetapi tiada wang akan dipindahkan untuk transaksi ini.</p>");
        f990a.put(bO.INTERNAL_ERROR, "Ralat Dalaman");
        f990a.put(bO.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Dengan mengklik butang di bawah, dengan ini saya bersetuju dengan terma-terma <a href='%1$s'>Perjanjian Pengguna PayPal</a> dan mengisytiharkan bahawa saya mematuhi undang-undang dan peraturan Jepun, termasuk sekatan terhadap bayaran ke Korea Utara dan Iran menurut <a href='%2$s'>Akta Pertukaran Asing dan Perdagangan Luar Negeri</a> untuk melengkapkan transaksi.</p>");
        f990a.put(bO.LOG_IN, "Log Masuk");
        f990a.put(bO.LOG_IN_TO_PAYPAL, "Log Masuk dengan PayPal");
        f990a.put(bO.LOG_OUT_BUTTON, "Log Keluar");
        f990a.put(bO.LOG_OUT, "Log keluar");
        f990a.put(bO.OK, "OK");
        f990a.put(bO.PASSWORD, "Kata Laluan");
        f990a.put(bO.PAY_AFTER_DELIVERY, "Bayar Selepas Penghantaran");
        f990a.put(bO.PAY_WITH, "Bayar dengan");
        f990a.put(bO.PAY_WITH_CARD, "Bayar dengan Kad");
        f990a.put(bO.PAYPAL_BALANCE, "Baki PayPal");
        f990a.put(bO.PHONE, "Telefon");
        f990a.put(bO.PIN, "PIN");
        f990a.put(bO.PREFERRED_PAYMENT_METHOD, "Kaedah Pembayaran Pilihan");
        f990a.put(bO.PRIVACY, "PayPal melindungi <a href='%s'>privasi</a> dan maklumat kewangan anda.");
        f990a.put(bO.PROCESSING, "Memproses");
        f990a.put(bO.REMEMBER_CARD, "Ingat kad");
        f990a.put(bO.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Simpanan");
        f990a.put(bO.SERVER_PROBLEM, "Terdapat masalah untuk berhubung dengan pelayan PayPal. Sila cuba semula.");
        f990a.put(bO.SESSION_EXPIRED_MESSAGE, "Sila log masuk semula ke PayPal.");
        f990a.put(bO.SESSION_EXPIRED_TITLE, "Sesi Telah Tamat Tempoh");
        f990a.put(bO.SHIPPING_ADDRESS, "Alamat Pengiriman");
        f990a.put(bO.STAY_LOGGED_IN, "Teruskan log masuk");
        f990a.put(bO.SYSTEM_ERROR_WITH_CODE, "Ralat sistem (%s). Sila cuba semula kemudian.");
        f990a.put(bO.TRY_AGAIN, "Cuba Semula");
        f990a.put(bO.TWO_FA_REQUIRED_ERROR, "Tidak dapat log masuk, kerana akaun anda telah diaktifkan dengan pengesahan dua faktor.");
        f990a.put(bO.UNAUTHORIZED_DEVICE_MESSAGE, "Bayaran dari peranti ini tidak dibenarkan.");
        f990a.put(bO.UNAUTHORIZED_DEVICE_TITLE, "Peranti Tidak Dibenarkan");
        f990a.put(bO.UNAUTHORIZED_MERCHANT_MESSAGE, "Bayaran kepada peniaga ini tidak dibenarkan (ID klien tidak sah).");
        f990a.put(bO.UNAUTHORIZED_MERCHANT_TITLE, "Peniaga tidak sah");
        f990a.put(bO.UNEXPECTED_PAYMENT_FLOW, "Terdapat masalah semasa memproses bayaran anda. Sila cuba semula.");
        f990a.put(bO.UNKNOWN_FUNDING_SOURCE, "Sumber Tidak Dikenali");
        f990a.put(bO.WE_ARE_SORRY, "Kami Memohon Maaf");
        f990a.put(bO.YOUR_ORDER, "Pesanan Anda");
        f990a.put(bO.CLEAR_CC_ALERT_TITLE, "Kosongkan Kad?");
        f990a.put(bO.CONSENT_FAILED_ALERT_TITLE, "Persetujuan Gagal");
        f990a.put(bO.CONNECTION_FAILED_TITLE, "Sambungan Gagal");
        f990a.put(bO.LOGIN_FAILED_ALERT_TITLE, "Log Masuk Gagal");
        f990a.put(bO.LOGIN_WITH_EMAIL, "Log masuk dengan kata laluan");
        f990a.put(bO.LOGIN_WITH_PHONE, "Log masuk dengan PIN");
        f990a.put(bO.ONE_MOMENT, "Sebentar\u2026");
        f990a.put(bO.PAY_FAILED_ALERT_TITLE, "Bayaran Gagal");
        f990a.put(bO.SCAN_CARD_ICON_DESCRIPTION, "Imbas");
        f990a.put(bO.VIA_LABEL, "Melalui");
        f990a.put(bO.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Ralat sistem. Sila cuba semula kemudian.");
        f991b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Perjanjian Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada wang akan dipindahkan.</p><p>Baki PayPal atau kad kredit atau kad debit utama anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan perjanjian ini, log masuk ke akaun PayPal anda dan pergi ke <strong>Profil</strong> &gt; <strong>Tetapan Saya</strong> &gt; <strong>Log Masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p>");
        f991b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Meluluskan terlebih dahulu bayaran masa depan yang dibuat dari <a href='%1$s'>akaun PayPal</a> anda.");
        f991b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Benarkan caj</a> untuk pembelian %2$s pada masa depan yang dibayar melalui PayPal. Anda mengarahkan PayPal untuk membayar semua amaun yang diminta oleh %3$s.</p><p>Sila lihat <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Bayaran Berulang dan Perjanjian Pengebilan PayPal</a> untuk maklumat lanjut.</p>");
        f991b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Kebenaran Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada bayaran akan dipindahkan.</p><p>Kaedah pembayaran lalai anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan kebenaran ini, log masuk ke akaun PayPal anda, pergi ke <strong>Profil</strong> &gt; <strong>Tetapan akaun saya</strong> &gt; <strong>Log masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p><p>Sila lihat bahagian \u201cBayaran Diluluskan Terlebih Dahulu\u201d dalam <a href='%s'>Perjanjian Pengguna PayPal</a> untuk maklumat lanjut.</p>");
        f991b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Kebenaran Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada bayaran akan dipindahkan.</p><p>Kaedah pembayaran lalai anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan kebenaran ini, log masuk ke akaun PayPal anda, pergi ke <strong>Profil</strong> &gt; <strong>Tetapan akaun saya</strong> &gt; <strong>Log masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p><p>Sila lihat bahagian \u201cBayaran Diluluskan Terlebih Dahulu\u201d dalam <a href='%s'>Perjanjian Pengguna PayPal</a> untuk maklumat lanjut.</p>");
        f991b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Perjanjian Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada wang akan dipindahkan.</p><p>Kaedah pembayaran lalai anda (baki PayPal, akaun bank terpaut, kad debit atau kad kredit anda, dalam aturan tersebut) akan digunakan untuk membayar pembelian melalui PayPal. Sila ambil perhatian, jika kaedah pembayaran lalai anda tidak mempunyai wang yang cukup untuk membayar pembelian tersebut, bank atau pembekal kad anda mungkin mengenakan yuran terhadap anda.</p><p>Untuk membatalkan perjanjian ini, log masuk ke akaun PayPal anda dan pergi ke <strong>Profil</strong>, kemudian klik <strong>Tetapan saya</strong> dan <strong>Ubah</strong> di sebelah \u201cLog masuk dengan PayPal.\u201d</p>");
        f991b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Perjanjian Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada wang akan dipindahkan.</p><p>Baki PayPal atau kad kredit atau kad debit utama anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan perjanjian ini, log masuk ke akaun PayPal anda dan pergi ke <strong>Profil</strong> &gt; <strong>Tetapan Saya</strong> &gt; <strong>Log Masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p>");
        f991b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Perjanjian Bayaran Masa Depan</strong></h1><p>PayPal akan menggunakan dahulu baki PayPal anda untuk membayar pembelian. Jika baki tidak mencukupi maka akaun bank, Kredit PayPal, kad debit, kad kredit dan/atau eCheck anda akan digunakan dalam pesanan tersebut.</p><p>Untuk membatalkan perjanjian ini, layari www.paypal.com <strong>Profil</strong> &gt; <strong>Tetapan Saya</strong> &gt; <strong>Log Masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p><p>Kebenaran bayaran kecil mungkin diperlukan untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan. Kebenaran akan dibatalkan dan anda tidak akan dikenakan caj.</p>");
        f991b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Perjanjian Bayaran Masa Depan</strong></h1><p>Untuk memastikan Akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada bayaran akan dipindahkan.</p><p>Kaedah pembayaran lalai anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan perjanjian ini, log masuk ke Akaun PayPal anda, pergi ke <strong>Profil</strong> &gt; <strong>Tetapan</strong> &gt; <strong>Log Masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p>");
        f991b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Kebenaran Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada bayaran akan dipindahkan.</p><p>Kaedah pembayaran lalai anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan kebenaran ini, log masuk ke akaun PayPal anda, pergi ke <strong>Profil</strong> &gt; <strong>Tetapan akaun saya</strong> &gt; <strong>Log masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p><p>Sila lihat bahagian \u201cBayaran Diluluskan Terlebih Dahulu\u201d dalam <a href='%s'>Perjanjian Pengguna PayPal</a> untuk maklumat lanjut.</p>");
        f991b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Benarkan caj</a> untuk pembelian %2$s pada masa depan yang dibayar melalui PayPal. Anda mengarahkan PayPal untuk membayar semua amaun yang diminta oleh %3$s.</p><p>Sila lihat <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Bayaran Berulang dan Perjanjian Pengebilan PayPal</a> untuk maklumat lanjut.</p>");
        f992c.put("INTERNAL_SERVICE_ERROR", "Ralat sistem. Sila cuba semula kemudian.");
        f992c.put("EXPIRED_CREDIT_CARD", "Kad telah tamat tempoh");
        f992c.put("EXPIRED_CREDIT_CARD_TOKEN", "Maklumat untuk kad ini tidak lagi terdapat dalam fail.\nSila serahkan semula.");
        f992c.put("INVALID_ACCOUNT_NUMBER", "Nombor akaun itu tidak wujud.");
        f992c.put("INVALID_RESOURCE_ID", "Ralat sistem. Sila cuba semula kemudian.");
        f992c.put("DUPLICATE_REQUEST_ID", "Ralat sistem. Sila cuba semula kemudian.");
        f992c.put("TRANSACTION_LIMIT_EXCEEDED", "Amaun melebihi had yang dibenarkan.");
        f992c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Bayaran balik yang diminta melebihi amaun transaksi asal.");
        f992c.put("REFUND_TIME_LIMIT_EXCEEDED", "Transaksi ini terlalu lama untuk dibayar balik.");
        f992c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Sebahagian daripada transaksi ini sudah dibayar balik.");
        f992c.put("TRANSACTION_ALREADY_REFUNDED", "Transaksi ini sudah dibayar balik.");
        f992c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Amaun melebihi had yang dibenarkan.");
        f992c.put("AUTHORIZATION_ALREADY_COMPLETED", "Kebenaran ini sudah dilengkapkan.");
        f992c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Hanya boleh membenarkan semula kebenaran asal, bukan kebenaran semula.");
        f992c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Kebenaran semula tidak dibenarkan dalam tempoh penunaian.");
        f992c.put("TOO_MANY_REAUTHORIZATIONS", "Tiada lagi kebenaran semula untuk kebenaran ini dibenarkan.");
        f992c.put("PERMISSION_DENIED", "Tiada keizinan untuk operasi yang diminta.");
        f992c.put("AUTHORIZATION_VOIDED", "Kebenaran telah dibatalkan.");
        f992c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "ID kebenaran yang diminta tidak wujud.");
        f992c.put("VALIDATION_ERROR", "Maklumat bayaran tidak sah. Sila betulkannya dan serahkan semula.");
        f992c.put("CREDIT_CARD_REFUSED", "Kad ditolak.");
        f992c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Maklumat kad tidak sah. Sila betulkannya dan serahkan semula.");
        f992c.put("PAYEE_ACCOUNT_RESTRICTED", "Vendor ini tidak boleh menerima bayaran buat masa ini.");
        f992c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Pembayar belum meluluskan bayaran.");
        f992c.put("INVALID_PAYER_ID", "Ralat sistem (ID Pembayar tidak sah). Sila cuba semula kemudian.");
        f992c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Vendor ini tidak boleh menerima bayaran buat masa ini.");
        f992c.put("PAYMENT_APPROVAL_EXPIRED", "Kelulusan bayaran telah tamat tempoh.");
        f992c.put("PAYMENT_EXPIRED", "Bayaran telah tamat tempoh.");
        f992c.put("DATA_RETRIEVAL", "Ralat sistem. Sila cuba semula kemudian.");
        f992c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Akaun penerima tidak mempunyai e-mel yang disahkan.");
        f992c.put("PAYMENT_STATE_INVALID", "Permintaan ini tidak sah akibat keadaan semasa bayaran tersebut.");
        f992c.put("TRANSACTION_REFUSED", "Transaksi ditolak.");
        f992c.put("AMOUNT_MISMATCH", "Jumlah amaun item kart tidak sepadan dengan amaun jualan.");
        f992c.put("CURRENCY_NOT_ALLOWED", "Mata wang ini tidak disokong oleh PayPal buat masa ini.");
        f992c.put("CURRENCY_MISMATCH", "Mata wang tahanan mesti sama dengan mata wang kebenaran.");
        f992c.put("AUTHORIZATION_EXPIRED", "Kebenaran telah tamat tempoh.");
        f992c.put("INVALID_ARGUMENT", "Transaksi ditolak kerana argumen tidak sah.");
        f992c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Tidak boleh mengakses maklumat kad yang disimpan.");
        f992c.put("CARD_TOKEN_PAYER_MISMATCH", "Tidak boleh mengakses maklumat kad yang disimpan.");
        f992c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Kebenaran dalam keadaan yang tidak boleh dibatalkan.");
        f992c.put("REQUIRED_SCOPE_MISSING", "Ralat sistem. Sila cuba semula kemudian.");
        f992c.put("UNAUTHORIZED_PAYMENT", "Peniaga tidak menerima jenis bayaran ini.");
        f992c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Mata wang tidak disokong untuk jenis kad.");
        f992c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Jenis kad tidak disokong.");
        f992c.put("INSUFFICIENT_FUNDS", "Pembeli tidak dapat membayar - baki akaun tidak mencukupi.");
        f992c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Keutamaan profil peniaga telah ditetapkan untuk menafikan transaksi tertentu secara automatik.");
        f992c.put("INVALID_FACILITATOR_CONFIGURATION", "Transaksi ini tidak boleh diproses akibat konfigurasi fasilitator tidak sah.");
        f992c.put("ORDER_ALREADY_COMPLETED", "Pesanan telah dibatalkan, tamat tempoh atau dilengkapkan.");
        f992c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Bilangan maksimum kebenaran yang dibenarkan untuk pesanan telah dicapai.");
        f992c.put("ORDER_VOIDED", "Pesanan telah dibatalkan.");
        f992c.put("ORDER_CANNOT_BE_VOIDED", "Pesanan dalam keadaan yang menghalang pembatalan.");
        f992c.put("ADDRESS_ADDITION_ERROR", "Ralat ditemui semasa menambah alamat pengiriman ke akaun PayPal.");
        f992c.put("INVALID_SHIPPING_ADDRESS", "Alamat penghantaran yang diberi tidak sah.");
        f992c.put("DUPLICATE_TRANSACTION", "Transaksi duplikasi.");
        f992c.put("AUTH_RC_RISK_FAILURE", "Ditolak kerana terdapat risiko.");
        f992c.put("AUTH_RC_OFAC_BLOCKED_IP", "Klien tidak dibenarkan.");
        f992c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Klien tidak dibenarkan.");
        f992c.put("invalid_user", "Nama pengguna/kata laluan salah. Sila cuba semula.");
        f992c.put("invalid_request", "Ralat telah berlaku.");
        f992c.put("unauthorized_client", "Permintaan tidak dibenarkan.");
        f992c.put("access_denied", "Permintaan tidak dibenarkan.");
        f992c.put("unsupported_response_type", "Ralat telah berlaku.");
        f992c.put("invalid_scope", "Permintaan tidak dibenarkan.");
        f992c.put("server_error", "Ralat sistem. Sila cuba semula kemudian.");
        f992c.put("temporarily_unavailable", "Ralat sistem. Sila cuba semula kemudian.");
    }

    public final String m895a() {
        return "ms";
    }

    public final /* synthetic */ String m896a(Enum enumR, String str) {
        bO bOVar = (bO) enumR;
        String str2 = bOVar.toString() + "|" + str;
        return f991b.containsKey(str2) ? (String) f991b.get(str2) : (String) f990a.get(bOVar);
    }

    public final String m897a(String str) {
        return (String) f992c.get(str);
    }
}
