package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

public final class aK implements at {
    private static Map f993a;
    private static Map f994b;
    private static Map f995c;

    static {
        f993a = new HashMap();
        f994b = new HashMap();
        f995c = new HashMap();
    }

    public aK() {
        f993a.put(bO.AND_OTHER_FUNDING_SOURCES, "og andre");
        f993a.put(bO.AUTHENTICATING, "Godkjenner");
        f993a.put(bO.BACK_BUTTON, "Tilbake");
        f993a.put(bO.BACKUP_FUNDING_SOURCE, "Reserve");
        f993a.put(bO.CANCEL, "Avbryt");
        f993a.put(bO.CARDTYPE_AMERICANEXPRESS, "American Express");
        f993a.put(bO.CARDTYPE_CARTAAURA, "Carta Aura");
        f993a.put(bO.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f993a.put(bO.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f993a.put(bO.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f993a.put(bO.CARDTYPE_COFINOGA, "Cofinoga");
        f993a.put(bO.CARDTYPE_DELTA, "Delta");
        f993a.put(bO.CARDTYPE_DISCOVER, "Discover");
        f993a.put(bO.CARDTYPE_ELECTRON, "Electron");
        f993a.put(bO.CARDTYPE_JCB, "JCB");
        f993a.put(bO.CARDTYPE_MAESTRO, "Maestro");
        f993a.put(bO.CARDTYPE_MASTERCARD, "MasterCard");
        f993a.put(bO.CARDTYPE_POSTEPAY, "Postepay");
        f993a.put(bO.CARDTYPE_4ETOILES, "4 \u00e9toiles");
        f993a.put(bO.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f993a.put(bO.CARDTYPE_VISA, "Visa");
        f993a.put(bO.CHANGE_PAYMENT_METHOD, "Endre betalingsmetode");
        f993a.put(bO.CHECKING_ACCOUNT_FOR_INSTITUTION, "Brukskonto");
        f993a.put(bO.CHECKING_DEVICE, "Kontrollerer denne enheten \u2026");
        f993a.put(bO.CLEAR_CREDIT_CARD_INFO, "Fjern kortopplysningene");
        f993a.put(bO.CONFIRM, "Bekreft");
        f993a.put(bO.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Er du sikker p\u00e5 at du vil fjerne kortopplysningene dine?");
        f993a.put(bO.CONFIRM_CHARGE_CREDIT_CARD, "Belast kortet");
        f993a.put(bO.CONFIRM_LOG_OUT, "Er du sikker p\u00e5 at du vil logge av PayPal?");
        f993a.put(bO.CONFIRM_SEND_PAYMENT, "Overf\u00f8r betaling");
        f993a.put(bO.CONSENT_AGREEMENT_AGREE, "Godta");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Opprettelsesdato for kontoen");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Kontostatus");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Kontotype");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adresse");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Aldersgruppe");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "F\u00f8dselsdato");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "E-postadresse");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Fullt navn");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Kj\u00f8nn");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Spr\u00e5k");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Norsk, Norge");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Tidssone");
        f993a.put(bO.CONSENT_AGREEMENT_ATTRIBUTES, "Del f\u00f8lgende: %s.");
        f993a.put(bO.CONSENT_AGREEMENT_INTRO, "%s ber om at du:");
        f993a.put(bO.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kj\u00f8p hos %2$s via PayPal. Du ber PayPal om \u00e5 betale alle summer som %3$s ber om.");
        f993a.put(bO.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Godta %1$s sine <a href='%2$s'>retningslinjer for personvern</a> og <a href='%3$s'>brukeravtale</a>.");
        f993a.put(bO.CONSENT_AGREEMENT_TITLE, "Samtykker");
        f993a.put(bO.EMAIL, "E-postadresse");
        f993a.put(bO.ENVIRONMENT_MOCK_DATA, "Eksempeldata");
        f993a.put(bO.ENVIRONMENT_SANDBOX, "Sandbox");
        f993a.put(bO.EXPIRES_ON_DATE, "Utl\u00f8per");
        f993a.put(bO.FORGOT_PASSWORD, "Har du glemt passordet?");
        f993a.put(bO.FROM_ACCOUNT, "Fra");
        f993a.put(bO.FUTURE_PAYMENT_METHOD_QUESTION, "Hvordan vil du finansiere fremtidige betalinger til %1$s er?");
        f993a.put(bO.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Den standard betalingskilden din brukes til \u00e5 utf\u00f8re fremtidige PayPal-betalinger for denne forhandleren.</p><p>Hvis du vil avbryte denne avtalen, logger du p\u00e5 PayPal-kontoen, g\u00e5r til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg p\u00e5 med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Regelmessig betaling-delen av <a href='%s'>PayPals brukeravtale</a> er gjeldende.</p><p>For \u00e5 kontrollere at betalinger fungerer med PayPal-kontoen din, kan denne appen simulere en liten pr\u00f8vetransaksjonen, men ingen penger overf\u00f8res.</p>");
        f993a.put(bO.INTERNAL_ERROR, "Intern feil");
        f993a.put(bO.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Ved \u00e5 klikke p\u00e5 knappen nedenfor, godtar jeg vilk\u00e5rene i <a href='%1$s'>PayPals brukeravtale</a> og jeg erkl\u00e6rer samtidig at jeg overholder japanske lover og forskrifter, herunder sanksjonsbestemmelser om betalinger til Nord-Korea og Iran, i tr\u00e5d med japansk <a href='%2$s'>lovgivning om handel med utenlandske produkter og valuta</a>, for \u00e5 fullf\u00f8re transaksjonen.</p>");
        f993a.put(bO.LOG_IN, "Logg p\u00e5");
        f993a.put(bO.LOG_IN_TO_PAYPAL, "Logg p\u00e5 med PayPal");
        f993a.put(bO.LOG_OUT_BUTTON, "Logg ut");
        f993a.put(bO.LOG_OUT, "Logg ut");
        f993a.put(bO.OK, "OK");
        f993a.put(bO.PASSWORD, "Passord");
        f993a.put(bO.PAY_AFTER_DELIVERY, "Betal etter levering");
        f993a.put(bO.PAY_WITH, "Betal med");
        f993a.put(bO.PAY_WITH_CARD, "Betal med kort");
        f993a.put(bO.PAYPAL_BALANCE, "PayPal-saldo");
        f993a.put(bO.PHONE, "Telefonnummer");
        f993a.put(bO.PIN, "PIN-kode");
        f993a.put(bO.PREFERRED_PAYMENT_METHOD, "Foretrukket betalingsmetode");
        f993a.put(bO.PRIVACY, "PayPal beskytter <a href='%s'>personvern</a>-opplysningene dine og den \u00f8konomiske informasjonen din.");
        f993a.put(bO.PROCESSING, "Behandler");
        f993a.put(bO.REMEMBER_CARD, "Husk kortet");
        f993a.put(bO.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Sparekonto");
        f993a.put(bO.SERVER_PROBLEM, "Det var et kommunikasjonsproblem med PayPal-serverne. Pr\u00f8v p\u00e5 nytt.");
        f993a.put(bO.SESSION_EXPIRED_MESSAGE, "Logg deg p\u00e5 PayPal p\u00e5 nytt.");
        f993a.put(bO.SESSION_EXPIRED_TITLE, "\u00d8kten er utl\u00f8pt");
        f993a.put(bO.SHIPPING_ADDRESS, "Leveringsadresse");
        f993a.put(bO.STAY_LOGGED_IN, "Forbli p\u00e5logget");
        f993a.put(bO.SYSTEM_ERROR_WITH_CODE, "Systemfeil (%s). Pr\u00f8v p\u00e5 nytt senere.");
        f993a.put(bO.TRY_AGAIN, "Pr\u00f8v p\u00e5 nytt");
        f993a.put(bO.TWO_FA_REQUIRED_ERROR, "Kan ikke logge p\u00e5, fordi p\u00e5loggingen til kontoen din har godkjenning med to faktorer.");
        f993a.put(bO.UNAUTHORIZED_DEVICE_MESSAGE, "Betaling fra denne enheten er ikke tillatt.");
        f993a.put(bO.UNAUTHORIZED_DEVICE_TITLE, "Uautorisert enhet");
        f993a.put(bO.UNAUTHORIZED_MERCHANT_MESSAGE, "Betalinger til denne forhandleren er ikke tillatt (ugyldig bruker-id).");
        f993a.put(bO.UNAUTHORIZED_MERCHANT_TITLE, "Ugyldig forhandler");
        f993a.put(bO.UNEXPECTED_PAYMENT_FLOW, "Det oppsto et problem ved behandlingen av betalingen. Pr\u00f8v p\u00e5 nytt.");
        f993a.put(bO.UNKNOWN_FUNDING_SOURCE, "Ukjent betalingsmetode");
        f993a.put(bO.WE_ARE_SORRY, "Vi beklager");
        f993a.put(bO.YOUR_ORDER, "Din bestilling");
        f993a.put(bO.CLEAR_CC_ALERT_TITLE, "Vil du fjerne kortet?");
        f993a.put(bO.CONSENT_FAILED_ALERT_TITLE, "Godkjenningen mislyktes");
        f993a.put(bO.CONNECTION_FAILED_TITLE, "Tilkobling mislykket");
        f993a.put(bO.LOGIN_FAILED_ALERT_TITLE, "P\u00e5logging mislyktes");
        f993a.put(bO.LOGIN_WITH_EMAIL, "Logg p\u00e5 med passord");
        f993a.put(bO.LOGIN_WITH_PHONE, "Logg p\u00e5 med PIN");
        f993a.put(bO.ONE_MOMENT, "Et \u00f8yeblikk \u2026");
        f993a.put(bO.PAY_FAILED_ALERT_TITLE, "Betaling mislyktes");
        f993a.put(bO.SCAN_CARD_ICON_DESCRIPTION, "Skann");
        f993a.put(bO.VIA_LABEL, "via");
        f993a.put(bO.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Systemfeil. Pr\u00f8v p\u00e5 nytt senere.");
        f994b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For \u00e5 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\u00f8vetransaksjon, men ingen penger overf\u00f8res.</p><p>PayPal-saldoen din eller det prim\u00e6re betalingskortet ditt brukes til \u00e5 betale for PayPal-kj\u00f8p.</p><p>Hvis du vil avbryte denne avtalen, logger du p\u00e5 PayPal-kontoen, g\u00e5r til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg p\u00e5 med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        f994b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Forh\u00e5ndsgodkjenn fremtidige betalinger fra <a href='%1$s'>PayPal-kontoen</a> din.");
        f994b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Godkjenn betalinger</a> for fremtidige kj\u00f8p hos %2$s via PayPal. Du ber PayPal om \u00e5 betale alle summer som %3$s ber om.</p><p>Du finner mer informasjon i <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPals avtale om regelmessige betalinger og fakturering</a>.</p>");
        f994b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For \u00e5 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\u00f8vetransaksjon, men ingen penger overf\u00f8res.</p><p>Betalingsmetoden du angir som standard brukes til \u00e5 betale for PayPal-kj\u00f8p.</p><p>Hvis du vil avbryte denne godkjenningen, logger du p\u00e5 PayPal-kontoen, g\u00e5r til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg p\u00e5 med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se \u2018Forh\u00e5ndsgodkjente betalinger\u2019-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        f994b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For \u00e5 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\u00f8vetransaksjon, men ingen penger overf\u00f8res.</p><p>Betalingsmetoden du angir som standard brukes til \u00e5 betale for PayPal-kj\u00f8p.</p><p>Hvis du vil avbryte denne godkjenningen, logger du p\u00e5 PayPal-kontoen, g\u00e5r til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg p\u00e5 med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se \u2018Forh\u00e5ndsgodkjente betalinger\u2019-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        f994b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For \u00e5 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\u00f8vetransaksjon, men ingen penger overf\u00f8res.</p><p>Din standard betalingsmetode (PayPal-saldo, tilknyttet bankkonto eller betalingskort, i denne rekkef\u00f8lgen) brukes til \u00e5 betale for PayPal-kj\u00f8p. V\u00e6r oppmerksom p\u00e5 at hvis den standard betalingsmetoden din ikke har nok penger til \u00e5 dekke kj\u00f8pet, kan banken eller kortleverand\u00f8ren belaste deg et gebyr.</p><p>For \u00e5 avbryte denne avtalen m\u00e5 du logge p\u00e5 PayPal-kontoen din og g\u00e5 til <strong>Profil</strong>, s\u00e5 klikker du p\u00e5 <strong>Mine innstillinger</strong> og <strong>Endre</strong> ved siden av \u2018Logg p\u00e5 med PayPal\u2019.</p>");
        f994b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For \u00e5 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\u00f8vetransaksjon, men ingen penger overf\u00f8res.</p><p>PayPal-saldoen din eller det prim\u00e6re betalingskortet ditt brukes til \u00e5 betale for PayPal-kj\u00f8p.</p><p>Hvis du vil avbryte denne avtalen, logger du p\u00e5 PayPal-kontoen, g\u00e5r til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg p\u00e5 med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        f994b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Vi fors\u00f8ker f\u00f8rst \u00e5 betale fra PayPal-saldoen din. Hvis det ikke er nok penger p\u00e5 den, fors\u00f8ker vi \u00e5 bruke bankkontoen din, PayPal Credit, betalingskort og/eller eCheck, i den viste rekkef\u00f8lgen. </p><p>Hvis du vil avbryte denne avtalen, g\u00e5r du til www.paypal.com <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg p\u00e5 med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Det kan v\u00e6re n\u00f8dvendig med en liten betalingsgodkjenning for \u00e5 kontrollere at PayPal-kontoen din kan belastes i fremtiden. Godkjenningen blir avbrutt, og du belastes ikke.</p>");
        f994b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For \u00e5 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\u00f8vetransaksjon, men ingen penger overf\u00f8res.</p><p>Betalingsmetoden du angir som standard brukes til \u00e5 betale for PayPal-kj\u00f8p.</p><p>Hvis du vil avbryte denne avtalen, logger du p\u00e5 PayPal-kontoen, g\u00e5r til <strong>Profil</strong> &gt; <strong>Innstillinger</strong> &gt; <strong>Logg p\u00e5 med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        f994b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For \u00e5 kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten pr\u00f8vetransaksjon, men ingen penger overf\u00f8res.</p><p>Betalingsmetoden du angir som standard brukes til \u00e5 betale for PayPal-kj\u00f8p.</p><p>Hvis du vil avbryte denne godkjenningen, logger du p\u00e5 PayPal-kontoen, g\u00e5r til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg p\u00e5 med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se \u2018Forh\u00e5ndsgodkjente betalinger\u2019-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        f994b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Godkjenn betalinger</a> for fremtidige kj\u00f8p hos %2$s via PayPal. Du ber PayPal om \u00e5 betale alle summer som %3$s ber om.</p><p>Du finner mer informasjon i <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPals avtale om regelmessige betalinger og fakturering</a>.</p>");
        f995c.put("INTERNAL_SERVICE_ERROR", "Systemfeil. Pr\u00f8v p\u00e5 nytt senere.");
        f995c.put("EXPIRED_CREDIT_CARD", "Kortet er utl\u00f8pt");
        f995c.put("EXPIRED_CREDIT_CARD_TOKEN", "Informasjonen for dette kortet er ikke lenger registrert.\nVennligst send p\u00e5 nytt.");
        f995c.put("INVALID_ACCOUNT_NUMBER", "Det kontonummeret finnes ikke.");
        f995c.put("INVALID_RESOURCE_ID", "Systemfeil. Pr\u00f8v p\u00e5 nytt senere.");
        f995c.put("DUPLICATE_REQUEST_ID", "Systemfeil. Pr\u00f8v p\u00e5 nytt senere.");
        f995c.put("TRANSACTION_LIMIT_EXCEEDED", "Bel\u00f8pet overskrider den tillatte grensen.");
        f995c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Den forespurte refusjonen overskrider bel\u00f8pet for den opprinnelige transaksjonen.");
        f995c.put("REFUND_TIME_LIMIT_EXCEEDED", "Denne transaksjonen er for gammel til at den kan refunderes.");
        f995c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Denne transaksjonen er allerede delvis refundert.");
        f995c.put("TRANSACTION_ALREADY_REFUNDED", "Denne transaksjonen er allerede refundert.");
        f995c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Bel\u00f8pet overskrider den tillatte grensen.");
        f995c.put("AUTHORIZATION_ALREADY_COMPLETED", "Denne godkjenningen er allerede fullf\u00f8rt.");
        f995c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Kan bare godkjenne den opprinnelige godkjenningen, ikke en ny godkjenning.");
        f995c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Ny godkjenning er ikke tillatt innenfor pr\u00f8veperioden.");
        f995c.put("TOO_MANY_REAUTHORIZATIONS", "Ingen flere nye godkjenninger er tillatt for denne godkjenningen.");
        f995c.put("PERMISSION_DENIED", "Ingen tillatelse til den forespurte operasjonen.");
        f995c.put("AUTHORIZATION_VOIDED", "Godkjenningen din er annullert.");
        f995c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Den forespurte godkjennings-IDen finnes ikke.");
        f995c.put("VALIDATION_ERROR", "Betalingsinformasjonen er ugyldig. Vi ber deg korrigere og sende inn p\u00e5 nytt.");
        f995c.put("CREDIT_CARD_REFUSED", "Kortet ble avvist.");
        f995c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Kortopplysningene er ugyldige. Vi ber deg korrigere og sende inn p\u00e5 nytt.");
        f995c.put("PAYEE_ACCOUNT_RESTRICTED", "Selgeren kan for \u00f8yeblikket ikke motta betalinger.");
        f995c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Betaleren har ikke godtatt betalingen.");
        f995c.put("INVALID_PAYER_ID", "Systemfeil (ugyldig betaler-id). Pr\u00f8v p\u00e5 nytt senere.");
        f995c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Selgeren kan for \u00f8yeblikket ikke motta betalinger.");
        f995c.put("PAYMENT_APPROVAL_EXPIRED", "Betalingsgodkjenningen er utl\u00f8pt.");
        f995c.put("PAYMENT_EXPIRED", "Betalingen er utl\u00f8pt.");
        f995c.put("DATA_RETRIEVAL", "Systemfeil. Pr\u00f8v p\u00e5 nytt senere.");
        f995c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Kontoen til betalingsmottakeren din har ikke en bekreftet e-post.");
        f995c.put("PAYMENT_STATE_INVALID", "Denne foresp\u00f8rselen er ugyldig p\u00e5 grunn av gjeldende status for betalingen.");
        f995c.put("TRANSACTION_REFUSED", "Transaksjonen ble avvist.");
        f995c.put("AMOUNT_MISMATCH", "Totalbel\u00f8pet for varene i handlekurven samsvarer ikke med kj\u00f8pesummen.");
        f995c.put("CURRENCY_NOT_ALLOWED", "Denne valutaen st\u00f8ttes for \u00f8yeblikket ikke av PayPal.");
        f995c.put("CURRENCY_MISMATCH", "Valuta for innhentingen m\u00e5 v\u00e6re lik valutaen for godkjenning.");
        f995c.put("AUTHORIZATION_EXPIRED", "Godkjenning utl\u00f8pt.");
        f995c.put("INVALID_ARGUMENT", "Transaksjon avvist p\u00e5 grunn av et ugyldig parameter");
        f995c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "F\u00e5r ikke tilgang til lagret kortinformasjonen.");
        f995c.put("CARD_TOKEN_PAYER_MISMATCH", "F\u00e5r ikke tilgang til lagret kortinformasjonen.");
        f995c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Godkjenningen er i et stadium som ikke kan bli annullert.");
        f995c.put("REQUIRED_SCOPE_MISSING", "Systemfeil. Pr\u00f8v p\u00e5 nytt senere.");
        f995c.put("UNAUTHORIZED_PAYMENT", "Forhandleren godtar ikke betalinger av denne typen.");
        f995c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valuta ikke st\u00f8ttet for korttypen.");
        f995c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Korttypen st\u00f8ttes ikke.");
        f995c.put("INSUFFICIENT_FUNDS", "Kj\u00f8peren kan ikke betale \u2013 ikke nok penger.");
        f995c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Forhandlerprofilen er innstilt til \u00e5 automatisk tilbakevise visse transaksjoner.");
        f995c.put("INVALID_FACILITATOR_CONFIGURATION", "Denne transaksjonen kan ikke behandles p\u00e5 grunn av en ugyldig systeminnretningskonfigurasjon.");
        f995c.put("ORDER_ALREADY_COMPLETED", "Bestillingen er allerede annullert, utl\u00f8pt eller fullf\u00f8rt.");
        f995c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Maksimalt antall tillatte godkjenninger for bestillingen er n\u00e5dd.");
        f995c.put("ORDER_VOIDED", "Bestillingen er blitt annullert.");
        f995c.put("ORDER_CANNOT_BE_VOIDED", "Det er ikke mulig \u00e5 annullere bestillingen i denne delen av prosessen.");
        f995c.put("ADDRESS_ADDITION_ERROR", "Det oppstod et problem i l\u00f8pet av prosessen med \u00e5 legge til en forsendelsesadresse i PayPal-kontoen.");
        f995c.put("INVALID_SHIPPING_ADDRESS", "Den oppgitte leveringsadressen er ikke gyldig.");
        f995c.put("DUPLICATE_TRANSACTION", "Duplikattransaksjon.");
        f995c.put("AUTH_RC_RISK_FAILURE", "Avvist grunnet risiko.");
        f995c.put("AUTH_RC_OFAC_BLOCKED_IP", "Klienten er ikke godkjent.");
        f995c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Klienten er ikke godkjent.");
        f995c.put("invalid_user", "Feil brukernavn/passord. Pr\u00f8v p\u00e5 nytt.");
        f995c.put("invalid_request", "Det har oppst\u00e5tt en feil.");
        f995c.put("unauthorized_client", "Ikke godkjent foresp\u00f8rsel.");
        f995c.put("access_denied", "Ikke godkjent foresp\u00f8rsel.");
        f995c.put("unsupported_response_type", "Det har oppst\u00e5tt en feil.");
        f995c.put("invalid_scope", "Ikke godkjent foresp\u00f8rsel.");
        f995c.put("server_error", "Systemfeil. Pr\u00f8v p\u00e5 nytt senere.");
        f995c.put("temporarily_unavailable", "Systemfeil. Pr\u00f8v p\u00e5 nytt senere.");
    }

    public final String m898a() {
        return "nb";
    }

    public final /* synthetic */ String m899a(Enum enumR, String str) {
        bO bOVar = (bO) enumR;
        String str2 = bOVar.toString() + "|" + str;
        return f994b.containsKey(str2) ? (String) f994b.get(str2) : (String) f993a.get(bOVar);
    }

    public final String m900a(String str) {
        return (String) f995c.get(str);
    }
}
