package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

public final class av implements at {
    private static Map f1032a;
    private static Map f1033b;
    private static Map f1034c;

    static {
        f1032a = new HashMap();
        f1033b = new HashMap();
        f1034c = new HashMap();
    }

    public av() {
        f1032a.put(bO.AND_OTHER_FUNDING_SOURCES, "og andre");
        f1032a.put(bO.AUTHENTICATING, "Godkender");
        f1032a.put(bO.BACK_BUTTON, "Tilbage");
        f1032a.put(bO.BACKUP_FUNDING_SOURCE, "Alternativ");
        f1032a.put(bO.CANCEL, "Annuller");
        f1032a.put(bO.CARDTYPE_AMERICANEXPRESS, "American Express");
        f1032a.put(bO.CARDTYPE_CARTAAURA, "Carta Aura");
        f1032a.put(bO.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f1032a.put(bO.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f1032a.put(bO.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f1032a.put(bO.CARDTYPE_COFINOGA, "Cofinoga");
        f1032a.put(bO.CARDTYPE_DELTA, "Delta");
        f1032a.put(bO.CARDTYPE_DISCOVER, "Discover");
        f1032a.put(bO.CARDTYPE_ELECTRON, "Electron");
        f1032a.put(bO.CARDTYPE_JCB, "JCB");
        f1032a.put(bO.CARDTYPE_MAESTRO, "Maestro");
        f1032a.put(bO.CARDTYPE_MASTERCARD, "MasterCard");
        f1032a.put(bO.CARDTYPE_POSTEPAY, "Postepay");
        f1032a.put(bO.CARDTYPE_4ETOILES, "4 \u00e9toiles");
        f1032a.put(bO.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f1032a.put(bO.CARDTYPE_VISA, "Visa");
        f1032a.put(bO.CHANGE_PAYMENT_METHOD, "Skift betalingsmetode");
        f1032a.put(bO.CHECKING_ACCOUNT_FOR_INSTITUTION, "Checkkonto");
        f1032a.put(bO.CHECKING_DEVICE, "Kontrollerer enheden \u2026");
        f1032a.put(bO.CLEAR_CREDIT_CARD_INFO, "Slet kortoplysninger");
        f1032a.put(bO.CONFIRM, "Bekr\u00e6ft");
        f1032a.put(bO.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Er du sikker p\u00e5, at du vil slette kortoplysningerne?");
        f1032a.put(bO.CONFIRM_CHARGE_CREDIT_CARD, "Debiter kort");
        f1032a.put(bO.CONFIRM_LOG_OUT, "Vil du logge af PayPal?");
        f1032a.put(bO.CONFIRM_SEND_PAYMENT, "Betal");
        f1032a.put(bO.CONSENT_AGREEMENT_AGREE, "Accepter");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Dato for oprettelse af konto");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Kontostatus");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Kontotype");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adresse");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Aldersgruppe");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "F\u00f8dselsdato");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "E-mailadresse");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Fulde navn");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "K\u00f8n");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Sprog");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Landestandard");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Tidszone");
        f1032a.put(bO.CONSENT_AGREEMENT_ATTRIBUTES, "Del f\u00f8lgende: %s.");
        f1032a.put(bO.CONSENT_AGREEMENT_INTRO, "%s beder dig om at:");
        f1032a.put(bO.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Godkende, at der tr\u00e6kkes penge</a> for fremtidige k\u00f8b hos %2$s, der betales via PayPal. Du beder os om at betale alle de bel\u00f8b, som %3$s anmoder om.");
        f1032a.put(bO.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Acceptere <a href='%2$s'>politikken om beskyttelse af personlige oplysninger</a> og <a href='%3$s'>brugeraftalen</a> for %1$s.");
        f1032a.put(bO.CONSENT_AGREEMENT_TITLE, "Samtykke");
        f1032a.put(bO.EMAIL, "E-mail");
        f1032a.put(bO.ENVIRONMENT_MOCK_DATA, "Simulerede data");
        f1032a.put(bO.ENVIRONMENT_SANDBOX, "Sandbox");
        f1032a.put(bO.EXPIRES_ON_DATE, "Udl\u00f8ber");
        f1032a.put(bO.FORGOT_PASSWORD, "Glemt adgangskoden?");
        f1032a.put(bO.FROM_ACCOUNT, "Fra");
        f1032a.put(bO.FUTURE_PAYMENT_METHOD_QUESTION, "Hvordan vil du gerne betale %1$s i fremtiden?");
        f1032a.put(bO.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Din foretrukne betalingsm\u00e5de bruges til at betale for fremtidige PayPal-betalinger til denne webbutik.</p><p>Hvis du vil annullere denne aftale, skal du logge p\u00e5 din PayPal-konto, g\u00e5 til <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log p\u00e5 med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Afsnittet Fast betaling i <a href='%s'>PayPals brugeraftale</a> finder anvendelse.</p><p>Appen kan simulere en lille pr\u00f8vetransaktion for at sikre, at du kan betale med din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p>");
        f1032a.put(bO.INTERNAL_ERROR, "Intern fejl");
        f1032a.put(bO.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Ved at klikke p\u00e5 knappen nedenfor accepterer jeg vilk\u00e5rene i <a href='%1$s'>PayPals brugeraftale</a>, og jeg erkl\u00e6rer mig i overensstemmelse med japanske love og regler, herunder sanktioner mod betalinger til Nordkorea og Iran i henhold til <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> for at gennemf\u00f8re transaktionen.</p>");
        f1032a.put(bO.LOG_IN, "Log p\u00e5");
        f1032a.put(bO.LOG_IN_TO_PAYPAL, "Log p\u00e5 med PayPal");
        f1032a.put(bO.LOG_OUT_BUTTON, "Log af");
        f1032a.put(bO.LOG_OUT, "Log af");
        f1032a.put(bO.OK, "OK");
        f1032a.put(bO.PASSWORD, "Adgangskode");
        f1032a.put(bO.PAY_AFTER_DELIVERY, "Betal efter levering");
        f1032a.put(bO.PAY_WITH, "Betal med");
        f1032a.put(bO.PAY_WITH_CARD, "Betal med kort");
        f1032a.put(bO.PAYPAL_BALANCE, "PayPal-saldo");
        f1032a.put(bO.PHONE, "Telefon");
        f1032a.put(bO.PIN, "Pinkode");
        f1032a.put(bO.PREFERRED_PAYMENT_METHOD, "Foretrukken betalingsmetode");
        f1032a.put(bO.PRIVACY, "Vi beskytter dine <a href='%s'>personlige oplysninger</a> og betalingsoplysninger.");
        f1032a.put(bO.PROCESSING, "Behandler");
        f1032a.put(bO.REMEMBER_CARD, "Husk kort");
        f1032a.put(bO.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Opsparingskonto");
        f1032a.put(bO.SERVER_PROBLEM, "Der kunne ikke oprettes forbindelse til vores servere. Pr\u00f8v igen.");
        f1032a.put(bO.SESSION_EXPIRED_MESSAGE, "Log p\u00e5 PayPal igen.");
        f1032a.put(bO.SESSION_EXPIRED_TITLE, "Sessionen er udl\u00f8bet");
        f1032a.put(bO.SHIPPING_ADDRESS, "Forsendelsesadresse");
        f1032a.put(bO.STAY_LOGGED_IN, "Forbliv logget p\u00e5");
        f1032a.put(bO.SYSTEM_ERROR_WITH_CODE, "Systemfejl (%s). Pr\u00f8v igen senere.");
        f1032a.put(bO.TRY_AGAIN, "Pr\u00f8v igen");
        f1032a.put(bO.TWO_FA_REQUIRED_ERROR, "Der kunne ikke logges p\u00e5, da to-faktor-godkendelse er aktiveret for din konto.");
        f1032a.put(bO.UNAUTHORIZED_DEVICE_MESSAGE, "Du kan ikke betale med denne enhed.");
        f1032a.put(bO.UNAUTHORIZED_DEVICE_TITLE, "Uautoriseret enhed");
        f1032a.put(bO.UNAUTHORIZED_MERCHANT_MESSAGE, "Du kan ikke betale denne webbutik (ugyldigt klient-id).");
        f1032a.put(bO.UNAUTHORIZED_MERCHANT_TITLE, "Ugyldig webbutik");
        f1032a.put(bO.UNEXPECTED_PAYMENT_FLOW, "Betalingen blev ikke behandlet. Pr\u00f8v igen.");
        f1032a.put(bO.UNKNOWN_FUNDING_SOURCE, "Ukendt betalingsmetode");
        f1032a.put(bO.WE_ARE_SORRY, "Vi beklager");
        f1032a.put(bO.YOUR_ORDER, "Din bestilling");
        f1032a.put(bO.CLEAR_CC_ALERT_TITLE, "Vil du slette kortet?");
        f1032a.put(bO.CONSENT_FAILED_ALERT_TITLE, "Samtykke mislykkedes");
        f1032a.put(bO.CONNECTION_FAILED_TITLE, "Der blev ikke oprettet forbindelse");
        f1032a.put(bO.LOGIN_FAILED_ALERT_TITLE, "Du blev ikke logget p\u00e5");
        f1032a.put(bO.LOGIN_WITH_EMAIL, "Log p\u00e5 med adgangskode");
        f1032a.put(bO.LOGIN_WITH_PHONE, "Log p\u00e5 med pinkode");
        f1032a.put(bO.ONE_MOMENT, "Et \u00f8jeblik \u2026");
        f1032a.put(bO.PAY_FAILED_ALERT_TITLE, "Betalingen blev ikke gennemf\u00f8rt.");
        f1032a.put(bO.SCAN_CARD_ICON_DESCRIPTION, "Skan");
        f1032a.put(bO.VIA_LABEL, "Via");
        f1032a.put(bO.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Systemfejl. Pr\u00f8v igen senere.");
        f1033b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Appen kan simulere en lille pr\u00f8vetransaktion for at kontrollere, at der kan tr\u00e6kkes penge p\u00e5 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din PayPal-saldo eller det prim\u00e6re betalingskort vil blive brugt, n\u00e5r du betaler med PayPal.</p><p>Hvis du vil annullere denne aftale, skal du logge p\u00e5 din PayPal-konto, g\u00e5 til <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log p\u00e5 med PayPal</strong> og fjerne denne webbutik fra listen.</p>");
        f1033b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Forh\u00e5ndsgodkende fremtidige betalinger fra din <a href='%1$s'>PayPal-konto</a>.");
        f1033b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Godkende, at der tr\u00e6kkes penge</a> for fremtidige k\u00f8b hos %2$s, der betales via PayPal. Du beder os om at betale alle de bel\u00f8b, som %3$s anmoder om.</p><p>L\u00e6s <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>vores aftale om faste betalinger og fakturering</a> for at f\u00e5 flere oplysninger.</p>");
        f1033b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Godkendelse af fremtidig betaling</strong></h1><p>Appen kan simulere en lille pr\u00f8vetransaktion for at sikre, at der kan tr\u00e6kkes penge p\u00e5 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, n\u00e5r du betaler med PayPal.</p><p>Hvis du vil annullere denne autorisation, skal du logge p\u00e5 din PayPal-konto, g\u00e5 til <strong>Min profil</strong> &gt; <strong>Mine kontoindstillinger</strong> &gt; <strong>Log p\u00e5 med PayPal</strong> og fjerne denne webbutik fra listen.</p><p>Du kan finde flere oplysninger i afsnittet \u201cForh\u00e5ndsgodkendte betalinger\u201d i <a href='%s'>vores brugeraftale</a>.</p>");
        f1033b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Godkendelse af fremtidig betaling</strong></h1><p>Appen kan simulere en lille pr\u00f8vetransaktion for at sikre, at der kan tr\u00e6kkes penge p\u00e5 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, n\u00e5r du betaler med PayPal.</p><p>Hvis du vil annullere denne autorisation, skal du logge p\u00e5 din PayPal-konto, g\u00e5 til <strong>Min profil</strong> &gt; <strong>Mine kontoindstillinger</strong> &gt; <strong>Log p\u00e5 med PayPal</strong> og fjerne denne webbutik fra listen.</p><p>Du kan finde flere oplysninger i afsnittet \u201cForh\u00e5ndsgodkendte betalinger\u201d i <a href='%s'>vores brugeraftale</a>.</p>");
        f1033b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Appen kan simulere en lille pr\u00f8vetransaktion for at sikre, at der kan tr\u00e6kkes penge p\u00e5 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode (din PayPal-saldo, din tilknyttede bankkonto eller dit betalingskort i denne r\u00e6kkef\u00f8lge) vil blive brugt, n\u00e5r du betaler med PayPal. Bem\u00e6rk, at din bank eller kortudsteder muligvis opkr\u00e6ver et gebyr, hvis der ikke er nok penge til at d\u00e6kke k\u00f8bet med din foretrukne betalingsmetode.</p><p>Hvis du vil annullere denne aftale, skal du logge p\u00e5 din PayPal-konto og g\u00e5 til <strong>Min profil</strong>. Klik derefter p\u00e5 <strong>Mine indstillinger</strong> og <strong>Skift</strong> ud for \u201cLog p\u00e5 med PayPal\u201d.</p>");
        f1033b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Appen kan simulere en lille pr\u00f8vetransaktion for at kontrollere, at der kan tr\u00e6kkes penge p\u00e5 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din PayPal-saldo eller det prim\u00e6re betalingskort vil blive brugt, n\u00e5r du betaler med PayPal.</p><p>Hvis du vil annullere denne aftale, skal du logge p\u00e5 din PayPal-konto, g\u00e5 til <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log p\u00e5 med PayPal</strong> og fjerne denne webbutik fra listen.</p>");
        f1033b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Vi bruger f\u00f8rst din PayPal-saldo for at betale for k\u00f8b. Hvis der ikke er penge nok, tr\u00e6kker vi penge p\u00e5 din bankkonto, PayPal Credit, dit betalingskort og/eller eCheck i den r\u00e6kkef\u00f8lge.</p><p>Hvis du vil annullere denne aftale, skal du g\u00e5 til www.paypal.com, v\u00e6lge <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log p\u00e5 med PayPal</strong> og fjerne denne webbutik fra listen.</p><p>Det kan v\u00e6re n\u00f8dvendigt, at du autoriserer en lille betaling for at kontrollere, at der kan tr\u00e6kkes penge p\u00e5 din PayPal-konto i fremtiden. Betalingen vil blive annulleret, og der vil ikke blive trukket nogen penge.</p>");
        f1033b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Appen kan simulere en lille pr\u00f8vetransaktion for at sikre, at der kan tr\u00e6kkes penge p\u00e5 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, n\u00e5r du betaler med PayPal.</p><p>Hvis du vil annullere denne aftale, skal du logge p\u00e5 din PayPal-konto og g\u00e5 til <strong>Min profil</strong> &gt; <strong>Indstillinger</strong> &gt; <strong>Log p\u00e5 med PayPal</strong> og fjerne denne webbutik fra listen.</p>");
        f1033b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Godkendelse af fremtidig betaling</strong></h1><p>Appen kan simulere en lille pr\u00f8vetransaktion for at sikre, at der kan tr\u00e6kkes penge p\u00e5 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, n\u00e5r du betaler med PayPal.</p><p>Hvis du vil annullere denne autorisation, skal du logge p\u00e5 din PayPal-konto, g\u00e5 til <strong>Min profil</strong> &gt; <strong>Mine kontoindstillinger</strong> &gt; <strong>Log p\u00e5 med PayPal</strong> og fjerne denne webbutik fra listen.</p><p>Du kan finde flere oplysninger i afsnittet \u201cForh\u00e5ndsgodkendte betalinger\u201d i <a href='%s'>vores brugeraftale</a>.</p>");
        f1033b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Godkende, at der tr\u00e6kkes penge</a> for fremtidige k\u00f8b hos %2$s, der betales via PayPal. Du beder os om at betale alle de bel\u00f8b, som %3$s anmoder om.</p><p>L\u00e6s <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>vores aftale om faste betalinger og fakturering</a> for at f\u00e5 flere oplysninger.</p>");
        f1034c.put("INTERNAL_SERVICE_ERROR", "Systemfejl. Pr\u00f8v igen senere.");
        f1034c.put("EXPIRED_CREDIT_CARD", "Kortet er udl\u00f8bet");
        f1034c.put("EXPIRED_CREDIT_CARD_TOKEN", "Oplysningerne for dette kort er ikke l\u00e6ngere gemt.\nSend igen.");
        f1034c.put("INVALID_ACCOUNT_NUMBER", "Kontonummeret findes ikke.");
        f1034c.put("INVALID_RESOURCE_ID", "Systemfejl. Pr\u00f8v igen senere.");
        f1034c.put("DUPLICATE_REQUEST_ID", "Systemfejl. Pr\u00f8v igen senere.");
        f1034c.put("TRANSACTION_LIMIT_EXCEEDED", "Bel\u00f8bet overstiger den tilladte gr\u00e6nse.");
        f1034c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Den anmodede tilbagebetaling overstiger det oprindelige bel\u00f8b.");
        f1034c.put("REFUND_TIME_LIMIT_EXCEEDED", "Du kan ikke l\u00e6ngere f\u00e5 tilbagebetalt denne transaktion.");
        f1034c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Denne transaktion er allerede blevet delvist tilbagebetalt.");
        f1034c.put("TRANSACTION_ALREADY_REFUNDED", "Transaktionen er allerede blevet tilbagebetalt.");
        f1034c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Bel\u00f8bet overstiger den tilladte gr\u00e6nse.");
        f1034c.put("AUTHORIZATION_ALREADY_COMPLETED", "Denne godkendelse er allerede blevet gennemf\u00f8rt.");
        f1034c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Du kan kun gentage den oprindelige godkendelse igen og ikke en allerede gentaget godkendelse.");
        f1034c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Du m\u00e5 ikke gentage en godkendelse igen inden for garantiperioden.");
        f1034c.put("TOO_MANY_REAUTHORIZATIONS", "Du m\u00e5 ikke gentage denne godkendelse flere gange.");
        f1034c.put("PERMISSION_DENIED", "Du har ikke tilladelse til at udf\u00f8re handlingen.");
        f1034c.put("AUTHORIZATION_VOIDED", "Din godkendelse er blevet ugyldiggjort.");
        f1034c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Det anmodede godkendelses-id findes ikke.");
        f1034c.put("VALIDATION_ERROR", "Betalingoplysningerne er ugyldige. Ret oplysningerne, og send dem igen.");
        f1034c.put("CREDIT_CARD_REFUSED", "Kortet blev afvist.");
        f1034c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Kortoplysningerne er ugyldige. Ret oplysningerne, og send dem igen.");
        f1034c.put("PAYEE_ACCOUNT_RESTRICTED", "Denne s\u00e6lger kan ikke tage imod betalinger i \u00f8jeblikket.");
        f1034c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Betaleren har ikke godkendt betalingen.");
        f1034c.put("INVALID_PAYER_ID", "Systemfejl (ugyldigt betaler-id). Pr\u00f8v igen senere.");
        f1034c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Denne s\u00e6lger kan ikke tage imod betalinger i \u00f8jeblikket.");
        f1034c.put("PAYMENT_APPROVAL_EXPIRED", "Godkendelsen af betalingen er udl\u00f8bet.");
        f1034c.put("PAYMENT_EXPIRED", "Betalingen er udl\u00f8bet.");
        f1034c.put("DATA_RETRIEVAL", "Systemfejl. Pr\u00f8v igen senere.");
        f1034c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Modtagers konto har ikke en bekr\u00e6ftet e-mail.");
        f1034c.put("PAYMENT_STATE_INVALID", "Denne anmodning er ugyldig p\u00e5 grund af den aktuelle tilstand for betaling.");
        f1034c.put("TRANSACTION_REFUSED", "Transaktionen blev afvist.");
        f1034c.put("AMOUNT_MISMATCH", "Bel\u00f8b i indk\u00f8bskurv stemmer ikke overens med salgsbel\u00f8b.");
        f1034c.put("CURRENCY_NOT_ALLOWED", "Denne valuta er i \u00f8jeblikket ikke underst\u00f8ttet af PayPal.");
        f1034c.put("CURRENCY_MISMATCH", "Valuta for indfangning skal v\u00e6re den samme som valutaen for tilladelsen.");
        f1034c.put("AUTHORIZATION_EXPIRED", "Godkendelse er udl\u00f8bet.");
        f1034c.put("INVALID_ARGUMENT", "Transaktion afvist p\u00e5 grund af et ugyldigt argument");
        f1034c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Kan ikke f\u00e5 adgang til gemte kortoplysninger.");
        f1034c.put("CARD_TOKEN_PAYER_MISMATCH", "Kan ikke f\u00e5 adgang til gemte kortoplysninger.");
        f1034c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Godkendelse er i en stat, der ikke kan v\u00e6re annulleret.");
        f1034c.put("REQUIRED_SCOPE_MISSING", "Systemfejl. Pr\u00f8v igen senere.");
        f1034c.put("UNAUTHORIZED_PAYMENT", "Du kan ikke bruge denne betalingsmetode i denne webbutik.");
        f1034c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Du kan ikke betale med kortet i denne valuta.");
        f1034c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Korttypen underst\u00f8ttes ikke.");
        f1034c.put("INSUFFICIENT_FUNDS", "K\u00f8ber kan ikke betale \u2013 utilstr\u00e6kkelige midler.");
        f1034c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Indstillingen for webbutikken er angivet til automatisk at afvise bestemte transaktioner.");
        f1034c.put("INVALID_FACILITATOR_CONFIGURATION", "Denne betaling kan ikke behandles p\u00e5 grund af en ugyldig formidlerkonfiguration.");
        f1034c.put("ORDER_ALREADY_COMPLETED", "Bestillingen er allerede blevet annulleret, er udl\u00f8bet eller er blevet sendt.");
        f1034c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Det maksimale antal autorisationer for bestillingen er n\u00e5et.");
        f1034c.put("ORDER_VOIDED", "Bestillingen er blevet annulleret.");
        f1034c.put("ORDER_CANNOT_BE_VOIDED", "Bestillingen kan ikke annulleres.");
        f1034c.put("ADDRESS_ADDITION_ERROR", "Der opstod fejl, da leveringsadressen blev f\u00f8jet til din PayPal-konto.");
        f1034c.put("INVALID_SHIPPING_ADDRESS", "Det angivne leveringsadresse er ugyldig.");
        f1034c.put("DUPLICATE_TRANSACTION", "Duplikeret betaling.");
        f1034c.put("AUTH_RC_RISK_FAILURE", "Afvist p\u00e5 grund af risiko.");
        f1034c.put("AUTH_RC_OFAC_BLOCKED_IP", "Klienten er ikke godkendt.");
        f1034c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Klienten er ikke godkendt.");
        f1034c.put("invalid_user", "Forkert brugernavn/adgangskode. Pr\u00f8v igen.");
        f1034c.put("invalid_request", "Der er opst\u00e5et en fejl.");
        f1034c.put("unauthorized_client", "Anmodningen blev ikke godkendt.");
        f1034c.put("access_denied", "Anmodningen blev ikke godkendt.");
        f1034c.put("unsupported_response_type", "Der er opst\u00e5et en fejl.");
        f1034c.put("invalid_scope", "Anmodningen blev ikke godkendt.");
        f1034c.put("server_error", "Systemfejl. Pr\u00f8v igen senere.");
        f1034c.put("temporarily_unavailable", "Systemfejl. Pr\u00f8v igen senere.");
    }

    public final String m940a() {
        return "da";
    }

    public final /* synthetic */ String m941a(Enum enumR, String str) {
        bO bOVar = (bO) enumR;
        String str2 = bOVar.toString() + "|" + str;
        return f1033b.containsKey(str2) ? (String) f1033b.get(str2) : (String) f1032a.get(bOVar);
    }

    public final String m942a(String str) {
        return (String) f1034c.get(str);
    }
}
