package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

public final class ay implements at {
    private static Map f1041a;
    private static Map f1042b;
    private static Map f1043c;

    static {
        f1041a = new HashMap();
        f1042b = new HashMap();
        f1043c = new HashMap();
    }

    public ay() {
        f1041a.put(bO.AND_OTHER_FUNDING_SOURCES, "& other");
        f1041a.put(bO.AUTHENTICATING, "Authenticating");
        f1041a.put(bO.BACK_BUTTON, "Back");
        f1041a.put(bO.BACKUP_FUNDING_SOURCE, "Backup");
        f1041a.put(bO.CANCEL, "Cancel");
        f1041a.put(bO.CARDTYPE_AMERICANEXPRESS, "American Express");
        f1041a.put(bO.CARDTYPE_CARTAAURA, "Carta Aura");
        f1041a.put(bO.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f1041a.put(bO.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f1041a.put(bO.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f1041a.put(bO.CARDTYPE_COFINOGA, "Cofinoga");
        f1041a.put(bO.CARDTYPE_DELTA, "Delta");
        f1041a.put(bO.CARDTYPE_DISCOVER, "Discover");
        f1041a.put(bO.CARDTYPE_ELECTRON, "Electron");
        f1041a.put(bO.CARDTYPE_JCB, "JCB");
        f1041a.put(bO.CARDTYPE_MAESTRO, "Maestro");
        f1041a.put(bO.CARDTYPE_MASTERCARD, "MasterCard");
        f1041a.put(bO.CARDTYPE_POSTEPAY, "Postepay");
        f1041a.put(bO.CARDTYPE_4ETOILES, "4 \u00e9toiles");
        f1041a.put(bO.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f1041a.put(bO.CARDTYPE_VISA, "Visa");
        f1041a.put(bO.CHANGE_PAYMENT_METHOD, "Change Payment Method");
        f1041a.put(bO.CHECKING_ACCOUNT_FOR_INSTITUTION, "Cheque Account");
        f1041a.put(bO.CHECKING_DEVICE, "Checking this device\u2026");
        f1041a.put(bO.CLEAR_CREDIT_CARD_INFO, "Clear card information");
        f1041a.put(bO.CONFIRM, "Confirm");
        f1041a.put(bO.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Are you sure you want to clear your card information?");
        f1041a.put(bO.CONFIRM_CHARGE_CREDIT_CARD, "Charge Card");
        f1041a.put(bO.CONFIRM_LOG_OUT, "Are you sure you want to log out of PayPal?");
        f1041a.put(bO.CONFIRM_SEND_PAYMENT, "Send Payment");
        f1041a.put(bO.CONSENT_AGREEMENT_AGREE, "Agree");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Account Creation Date");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Account Status");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Account Type");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Address");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Age Range");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Date of Birth");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Email address");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Full Name");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Gender");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Language");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Locale");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Phone Number");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Time Zone");
        f1041a.put(bO.CONSENT_AGREEMENT_ATTRIBUTES, "Share the following: %s.");
        f1041a.put(bO.CONSENT_AGREEMENT_INTRO, "%s asks that you:");
        f1041a.put(bO.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Authorise charges</a> for future %2$s purchases paid for with PayPal. You instruct PayPal to pay all amounts requested by %3$s.");
        f1041a.put(bO.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Agree to the %1$s <a href='%2$s'>privacy policy</a> and <a href='%3$s'>user agreement</a>.");
        f1041a.put(bO.CONSENT_AGREEMENT_TITLE, "Consent");
        f1041a.put(bO.EMAIL, "Email");
        f1041a.put(bO.ENVIRONMENT_MOCK_DATA, "Mock Data");
        f1041a.put(bO.ENVIRONMENT_SANDBOX, "Sandbox");
        f1041a.put(bO.EXPIRES_ON_DATE, "Expires");
        f1041a.put(bO.FORGOT_PASSWORD, "Forgotten your password?");
        f1041a.put(bO.FROM_ACCOUNT, "From");
        f1041a.put(bO.FUTURE_PAYMENT_METHOD_QUESTION, "How would you like to fund future payments to %1$s?");
        f1041a.put(bO.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Future Payment Agreement</strong></h1><p>Your default payment method will be used to pay for future PayPal payments from this merchant.</p><p>To cancel this agreement, log in to your PayPal account, go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p><p>The Recurring Payment section of the <a href='%s'>PayPal User Agreement</a> shall apply.</p><p>To make sure payments work with your PayPal account, this app may simulate a small test transaction, but no money will be transferred for this.</p>");
        f1041a.put(bO.INTERNAL_ERROR, "Internal Error");
        f1041a.put(bO.JAPANESE_COMPLIANCE_AGREEMENT, "<p>By clicking the button below, I hereby agree to the terms of the <a href='%1$s'>PayPal User Agreement</a> and declare that I am in compliance with Japanese laws and regulations, including sanctions against payments to North Korea and Iran pursuant to the <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> to complete the transaction.</p>");
        f1041a.put(bO.LOG_IN, "Log In");
        f1041a.put(bO.LOG_IN_TO_PAYPAL, "Log In with PayPal");
        f1041a.put(bO.LOG_OUT_BUTTON, "Log out");
        f1041a.put(bO.LOG_OUT, "Log out");
        f1041a.put(bO.OK, "OK");
        f1041a.put(bO.PASSWORD, "Password");
        f1041a.put(bO.PAY_AFTER_DELIVERY, "Pay After Delivery");
        f1041a.put(bO.PAY_WITH, "Pay with");
        f1041a.put(bO.PAY_WITH_CARD, "Pay with Card");
        f1041a.put(bO.PAYPAL_BALANCE, "PayPal Balance");
        f1041a.put(bO.PHONE, "Phone");
        f1041a.put(bO.PIN, "PIN");
        f1041a.put(bO.PREFERRED_PAYMENT_METHOD, "Preferred Payment Method");
        f1041a.put(bO.PRIVACY, "PayPal protects your <a href='%s'>privacy</a> and financial information.");
        f1041a.put(bO.PROCESSING, "Processing");
        f1041a.put(bO.REMEMBER_CARD, "Remember card");
        f1041a.put(bO.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Savings Account");
        f1041a.put(bO.SERVER_PROBLEM, "There was a problem communicating with the PayPal servers. Please try again.");
        f1041a.put(bO.SESSION_EXPIRED_MESSAGE, "Please log in to PayPal again.");
        f1041a.put(bO.SESSION_EXPIRED_TITLE, "Session expired.");
        f1041a.put(bO.SHIPPING_ADDRESS, "Shipping Address");
        f1041a.put(bO.STAY_LOGGED_IN, "Stay logged in");
        f1041a.put(bO.SYSTEM_ERROR_WITH_CODE, "System error (%s). Please try again later.");
        f1041a.put(bO.TRY_AGAIN, "Try Again");
        f1041a.put(bO.TWO_FA_REQUIRED_ERROR, "Unable to log in because two-factor authentication has been enabled for your account.");
        f1041a.put(bO.UNAUTHORIZED_DEVICE_MESSAGE, "Payments from this device are not allowed.");
        f1041a.put(bO.UNAUTHORIZED_DEVICE_TITLE, "Unauthorised Device");
        f1041a.put(bO.UNAUTHORIZED_MERCHANT_MESSAGE, "Payments to this merchant are not allowed (invalid clientId).");
        f1041a.put(bO.UNAUTHORIZED_MERCHANT_TITLE, "Invalid merchant");
        f1041a.put(bO.UNEXPECTED_PAYMENT_FLOW, "There was a problem processing your payment. Please try again.");
        f1041a.put(bO.UNKNOWN_FUNDING_SOURCE, "Unrecognised Source");
        f1041a.put(bO.WE_ARE_SORRY, "We\u2019re Sorry");
        f1041a.put(bO.YOUR_ORDER, "Your Order");
        f1041a.put(bO.CLEAR_CC_ALERT_TITLE, "Clear Card?");
        f1041a.put(bO.CONSENT_FAILED_ALERT_TITLE, "Consent Failed");
        f1041a.put(bO.CONNECTION_FAILED_TITLE, "Connection Failed");
        f1041a.put(bO.LOGIN_FAILED_ALERT_TITLE, "Login Failed");
        f1041a.put(bO.LOGIN_WITH_EMAIL, "Log in with password");
        f1041a.put(bO.LOGIN_WITH_PHONE, "Log in with PIN");
        f1041a.put(bO.ONE_MOMENT, "One moment\u2026");
        f1041a.put(bO.PAY_FAILED_ALERT_TITLE, "Payment Failed");
        f1041a.put(bO.SCAN_CARD_ICON_DESCRIPTION, "Scan");
        f1041a.put(bO.VIA_LABEL, "Via");
        f1041a.put(bO.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "System error. Please try again later.");
        f1042b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no money will be transferred.</p><p>Your PayPal balance or primary credit or debit card will be used to pay for PayPal purchases.</p><p>To cancel this agreement, log in to your PayPal account and go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p>");
        f1042b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Pre-approve future payments made from your <a href='%1$s'>PayPal account</a>.");
        f1042b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Authorise charges</a> for future %2$s purchases paid for with PayPal. You instruct PayPal to pay all amounts requested by %3$s.</p><p>Please see the <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPal Recurring Payments and Billing Agreement</a> for more information.</p>");
        f1042b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Future Payment authorisation</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no payment will be transferred.</p><p>Your default payment method will be used to pay for PayPal purchases.</p><p>To cancel this authorisation, log in to your PayPal account, go to <strong>Profile</strong> &gt; <strong>My account settings</strong> &gt; <strong>Log in with PayPal</strong> and remove this merchant from the list.</p><p>Please see the \u201cPre-approved Payments\u201d section of the <a href='%s'>PayPal User Agreement</a> for more information.</p>");
        f1042b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Future Payment authorisation</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no payment will be transferred.</p><p>Your default payment method will be used to pay for PayPal purchases.</p><p>To cancel this authorisation, log in to your PayPal account, go to <strong>Profile</strong> &gt; <strong>My account settings</strong> &gt; <strong>Log in with PayPal</strong> and remove this merchant from the list.</p><p>Please see the \u201cPre-approved Payments\u201d section of the <a href='%s'>PayPal User Agreement</a> for more information.</p>");
        f1042b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal account can be charged in future, this app may simulate a small test transaction but no money will be transferred.</p><p>Your default payment method (your PayPal balance, linked bank account, credit or debit card, in that order) will be used to pay for PayPal purchases. Please note, if your default payment method doesn\u2019t have enough funds to cover the purchase, your bank or card provider may charge you a fee.</p><p>To cancel this agreement, log in to your PayPal account and go to <strong>Profile</strong> then click <strong>My settings</strong> and <strong>Change</strong> beside \u201cLog in with PayPal.\u201d</p>");
        f1042b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no money will be transferred.</p><p>Your PayPal balance or primary credit or debit card will be used to pay for PayPal purchases.</p><p>To cancel this agreement, log in to your PayPal account and go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p>");
        f1042b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Future Payment Agreement</strong></h1><p>PayPal will first use your PayPal balance to pay for purchases. If that doesn\u2019t cover the total, your bank account, PayPal Credit, debit card, credit card and/or eCheque will be used in that order.</p><p>To cancel this agreement, go to www.paypal.com.au <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p><p>A small payment authorisation may be required to make sure your PayPal account can be charged in the future. The authorisation will be voided and you won\u2019t be charged.</p>");
        f1042b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal Account can be charged in the future, this app may simulate a small test transaction but no payment will be transferred.</p><p>Your default payment method will be used to pay for PayPal purchases.</p><p>To cancel this agreement, log in to your PayPal Account, go to <strong>Profile</strong> &gt; <strong>Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p>");
        f1042b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Future Payment authorisation</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no payment will be transferred.</p><p>Your default payment method will be used to pay for PayPal purchases.</p><p>To cancel this authorisation, log in to your PayPal account, go to <strong>Profile</strong> &gt; <strong>My account settings</strong> &gt; <strong>Log in with PayPal</strong> and remove this merchant from the list.</p><p>Please see the \u201cPre-approved Payments\u201d section of the <a href='%s'>PayPal User Agreement</a> for more information.</p>");
        f1042b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Authorise charges</a> for future %2$s purchases paid for with PayPal. You instruct PayPal to pay all amounts requested by %3$s.</p><p>Please see the <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPal Recurring Payments and Billing Agreement</a> for more information.</p>");
        f1043c.put("INTERNAL_SERVICE_ERROR", "System error. Please try again later.");
        f1043c.put("EXPIRED_CREDIT_CARD", "Card has expired");
        f1043c.put("EXPIRED_CREDIT_CARD_TOKEN", "The information for this card is no longer on file.\nPlease submit again.");
        f1043c.put("INVALID_ACCOUNT_NUMBER", "That account number does not exist.");
        f1043c.put("INVALID_RESOURCE_ID", "System error. Please try again later.");
        f1043c.put("DUPLICATE_REQUEST_ID", "System error. Please try again later.");
        f1043c.put("TRANSACTION_LIMIT_EXCEEDED", "The amount exceeds the allowable limit.");
        f1043c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "The requested refund exceeds the amount of the original transaction.");
        f1043c.put("REFUND_TIME_LIMIT_EXCEEDED", "This transaction is too old to refund.");
        f1043c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "This transaction has already been partially refunded.");
        f1043c.put("TRANSACTION_ALREADY_REFUNDED", "This transaction has already been refunded.");
        f1043c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "The amount exceeds the allowable limit.");
        f1043c.put("AUTHORIZATION_ALREADY_COMPLETED", "This authorisation has already been completed.");
        f1043c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Can only reauthorise the original authorisation, not a reauthorisation.");
        f1043c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Reauthorisation is not allowed within the honour period.");
        f1043c.put("TOO_MANY_REAUTHORIZATIONS", "No more reauthorisations for this authorisation are allowed.");
        f1043c.put("PERMISSION_DENIED", "No permission for the requested operation.");
        f1043c.put("AUTHORIZATION_VOIDED", "authorisation has been voided.");
        f1043c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "The requested authorisation ID does not exist.");
        f1043c.put("VALIDATION_ERROR", "The payment information is invalid. Please correct and submit again.");
        f1043c.put("CREDIT_CARD_REFUSED", "Card declined.");
        f1043c.put("CREDIT_CARD_CVV_CHECK_FAILED", "The card information is invalid. Please correct and submit again.");
        f1043c.put("PAYEE_ACCOUNT_RESTRICTED", "This vendor cannot receive payments at this time.");
        f1043c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Payer has not approved payment.");
        f1043c.put("INVALID_PAYER_ID", "System error (invalid Payer ID). Please try again later.");
        f1043c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "This vendor cannot receive payments at this time.");
        f1043c.put("PAYMENT_APPROVAL_EXPIRED", "Payment approval has expired.");
        f1043c.put("PAYMENT_EXPIRED", "The payment has expired.");
        f1043c.put("DATA_RETRIEVAL", "System error. Please try again later.");
        f1043c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Payee account does not have a confirmed email address.");
        f1043c.put("PAYMENT_STATE_INVALID", "This request is invalid due to the current state of the payment.");
        f1043c.put("TRANSACTION_REFUSED", "The transaction was denied.");
        f1043c.put("AMOUNT_MISMATCH", "Cart item amount total does not match sale amount.");
        f1043c.put("CURRENCY_NOT_ALLOWED", "This currency is not currently supported by PayPal.");
        f1043c.put("CURRENCY_MISMATCH", "Currency of capture must be the same as currency of authorisation.");
        f1043c.put("AUTHORIZATION_EXPIRED", "Authorisation has expired.");
        f1043c.put("INVALID_ARGUMENT", "Transaction denied because of an invalid argument");
        f1043c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Cannot access saved card information.");
        f1043c.put("CARD_TOKEN_PAYER_MISMATCH", "Cannot access saved card information.");
        f1043c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Authorisation is in a state that cannot be voided.");
        f1043c.put("REQUIRED_SCOPE_MISSING", "System error. Please try again later.");
        f1043c.put("UNAUTHORIZED_PAYMENT", "The merchant does not accept payments of this type.");
        f1043c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Currency not supported for card type.");
        f1043c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Card type not supported.");
        f1043c.put("INSUFFICIENT_FUNDS", "Buyer cannot pay \u2013 insufficient funds.");
        f1043c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Merchant profile preference is set to automatically deny certain transactions.");
        f1043c.put("INVALID_FACILITATOR_CONFIGURATION", "This transaction cannot be processed due to an invalid facilitator configuration.");
        f1043c.put("ORDER_ALREADY_COMPLETED", "Order has already been voided or completed, or has expired.");
        f1043c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Maximum number of allowed authorisations for the order has been reached.");
        f1043c.put("ORDER_VOIDED", "Order has been voided.");
        f1043c.put("ORDER_CANNOT_BE_VOIDED", "Order is in a state which prevents voiding.");
        f1043c.put("ADDRESS_ADDITION_ERROR", "Error encountered while adding shipping address to PayPal account.");
        f1043c.put("INVALID_SHIPPING_ADDRESS", "The shipping address provided is not valid.");
        f1043c.put("DUPLICATE_TRANSACTION", "Duplicate transaction.");
        f1043c.put("AUTH_RC_RISK_FAILURE", "Declined due to risk.");
        f1043c.put("AUTH_RC_OFAC_BLOCKED_IP", "Client not authorised.");
        f1043c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Client not authorised.");
        f1043c.put("invalid_user", "Incorrect username/password. Please try again.");
        f1043c.put("invalid_request", "An error has occurred.");
        f1043c.put("unauthorized_client", "Request not authorised.");
        f1043c.put("access_denied", "Request not authorised.");
        f1043c.put("unsupported_response_type", "An error has occurred.");
        f1043c.put("invalid_scope", "Request not authorised.");
        f1043c.put("server_error", "System error. Please try again later.");
        f1043c.put("temporarily_unavailable", "System error. Please try again later.");
    }

    public final String m949a() {
        return "en_AU";
    }

    public final /* synthetic */ String m950a(Enum enumR, String str) {
        bO bOVar = (bO) enumR;
        String str2 = bOVar.toString() + "|" + str;
        return f1042b.containsKey(str2) ? (String) f1042b.get(str2) : (String) f1041a.get(bOVar);
    }

    public final String m951a(String str) {
        return (String) f1043c.get(str);
    }
}
