package io.card.payment;

public enum ap {
    APP_NOT_AUTHORIZED_MESSAGE,
    CANCEL,
    CARDTYPE_AMERICANEXPRESS,
    CARDTYPE_DISCOVER,
    CARDTYPE_JCB,
    CARDTYPE_MASTERCARD,
    CARDTYPE_VISA,
    DONE,
    ENTRY_CVV,
    ENTRY_POSTAL_CODE,
    ENTRY_EXPIRES,
    ENTRY_NUMBER,
    ENTRY_TITLE,
    EXPIRES_PLACEHOLDER,
    OK,
    SCAN_GUIDE,
    KEYBOARD,
    ENTRY_CARD_NUMBER,
    MANUAL_ENTRY_TITLE,
    WHOOPS,
    ERROR_NO_DEVICE_SUPPORT,
    ERROR_CAMERA_CONNECT_FAIL,
    ERROR_CAMERA_UNEXPECTED_FAIL
}
